### ISSUE TITLE
FIX THE GODDAMN SEARCH BAR

### ISSUE THREAD

**Issue by D0nnieD4rk0** [philc/vimium#3824] opened 2021-05-29 20:45 UTC
whenever u start searching for a word which has the first letter in more than 100 instances bugs the thing out and locks you on that first letter not letting you type anything else.. it happens often enough to get me writing this issue on github (btw move to | beam next to the forward slash)

**Comment by gdh1995** [comment] 2021-05-30 02:46
Seems a duplicate of #3774 , and will be fixed by #3801 .

**Closed** 2021-07-03 06:36 UTC
