### ISSUE TITLE
Support following link in external browser and/or passing url to external script

### ISSUE THREAD

**Issue by anderspapitto** [philc/vimium#1787] opened 2015-08-08 23:28 UTC
Using the standard f/F link hint functionality, I would like to be able to open links in, e.g. Firefox, or (what I actually want), in a new window launched with `chromium --app=$URL`.

Looking through the documentation/release notes/issue tracker, I haven't come across a way to generalize link-following in this way.

**Comment by mrmr1993** [comment] 2015-08-09 02:13
There are a few things to contend with here:
* Chrome extensions can't run external commands, by design.
  - the common workaround for this is to run a server on your local machine (so that eg. visiting `http://localhost:12345/open_url?url=your_encoded_url_here` opens the url with your desired command), and then you request the url in the browser to run the command.
* Vimium doesn't currently support custom commands in any form.
 - Issue #1392 relates to this.
 - Integrating a custom command with link hints will be harder still, because we would have to then expose those parts of our code as an API (and IMHO that code's a bit of a mess).

A usable &mdash; but less convenient &mdash; workaround would be to create a bookmarklet with something that translates clicks on links into visits to the local serverserver, use that via the Vomnibar (mapped to `b`), and then use normal link hints for the desired result. For example (untested):

```js
javascript:window.addEventListener("click",function(event){
  var target = event.target;
  if (!target || target.tagName.toUpperCase() != "A" || !target.hasAttribute("href")) {
    return true;
  }
  var loader = document.createElement("img");
  loader.src = "http://localhost:12345/open_url?url=" + encodeURIComponent(target.getAttribute("href"));
  var removeOnLoad = function(){loader.parentElement.removeChild(loader);};
  loader.addEventListener("load", removeOnLoad);
  loader.addEventListener("error", removeOnLoad);
  document.body.appendChild(loader);
  window.removeEventListener("click", arguments.callee, true);
  event.preventDefault();
  event.stopPropagation();
}, true);
```

Setting this as a bookmarklet named `oiep` (open in external program) should then let you run the command by typing `boiep<enter>f<link hints keys here>`. Hope this helps!

**Comment by anderspapitto** [comment] 2015-08-09 03:02
Thank you, that is quite helpful. I hadn't considered a local webserver, which seems like a pretty neat solution. The lack of custom commands is definitely still an issue, but I might try to work around it for now by forking vimium and hardcoding the localhost-redirection into the link hint code.

**Comment by mrmr1993** [comment] 2015-08-09 04:14
@anderspapitto you may find it easier to fork #1761, and add

```coffee
OPEN_EXTERNAL =
  name: "frame"
  indicator: "Open link in an external program."
  linkActivator: (link, rect, callbackObject) ->
    if (DomUtils.isSelectable(link))
      DomUtils.simulateSelect(link)
    else
      if (link.nodeName.toLowerCase() == "input" and link.type not in ["button", "submit"])
        link.focus()
      DomUtils.flashRect(rect)
      if link.tagName.toUpperCase() == " A" and link.hasProperty "href"
        xmlHttpRequest = new XMLHttpRequest()
        xmlHttpRequest.open "GET", http://localhost:12345/open_url?url=#{encodeURIComponent link.getAttribute "href"}"
        xmlHttpRequest.send()
      else
        DomUtils.simulateClick link

...

  activateModeToOpenExternally: @activateMode OPEN_EXTERNAL
```

to the relevant places in `link_hints.coffee`, and

```coffee
"LinkHints.activateModeToOpenExternally": ["Open a link in an external program", { noRepeat: true }]
```

to `commandDescriptions` in `commands.coffee`. At least, this is the kind of thing I created that PR to support!

**Comment by anderspapitto** [comment] 2015-08-14 21:08
thanks again mrmr. I'll probably do that if I need more advanced functionality.

For now though, I satisfied my particular use case by a quick patch to vimium to always open in a new chrome app window. In case anyone is interested, it's here https://github.com/anderspapitto/vimium/commit/bbf7512629882da88dd5e9a4f07d9e8df6c4700f

**Comment by smblott-github** [comment] 2015-08-15 05:48
I'll close this - there's probably not a general Vimium solution.
Shout if that's not the right thing to do.

**Closed by smblott-github** 2015-08-15 05:48 UTC

**Comment by rrsahutwo** [comment] 2015-11-13 10:39
The perform definitely requires some expert assistance otherwise perhaps you will have to face a lot of troubles or maybe you are likely to mess up all your useful factors during moving them. Hiring the effective solutions of best packers and movers in Bangalore can be of great help for you in residential and commercial shifting needs from your previous position to new one. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:39
We are the knowledgeable experts to create the journey safe and practical with the expertise in product packaging, running and moving solutions. We are expert solutions company. 100% client care in safe and a hassle-free shifting are ultimate Bangalore of we. Everyone from the town of Bangalore or other places across the nation can confidently look for Care India Takes effective expert solutions while preparing for moving products and moving the place

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:39
As a resident of Bangalore or other places of India, if you are one of those individuals who are preparing for moving, Bangalore packers and movers at Care India Packers would be the best option for your need. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:39
The experts will not only help you create the automobile available, but also we will help you product packaging and running. If you can let our qualified experts do these works for you, you will be pleased after getting your purpose fulfilled. In your need, you will discover the appropriate information about the automobiles and solutions available here just for you. We are well-known movers packers Bangalore at the well-known movers in your area. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
