### ISSUE TITLE
Wrong link hint positions on HiDPI screens

### ISSUE THREAD

**Issue by Lazarus535** [philc/vimium#2635] opened 2017-09-11 11:17 UTC
Explanation:
Just setup chromium/vimium on my new notebook (2560x1440 screen).
I use the "--force-device-scale-factor=2" cmdline option to scale the browser.
However i get wrong positions of the link hints (when pressing 'f').
Link hint posistions are initially right where they should be, but "drift up" when the page is scrolled down.

How to reproduce:
Start chromium with "--force-device-scale-factor=2".
Install vimium (if not already).
Open some site.
Scroll down a bit.
Press 'f'.
See the wrong link hint positions.
(See attached images for expanation, further down pictures represent further "scrolled-down" states).

Further explanation:
Use either "--force-device-scale-factor=2"
OR
set Xft.dpi: 192
in ~/.Xresources
(this is how i discovered it, nice option to make GUIs scale and chromium reads this value)
(both have the same effect, but for reproduction the bug, option number 1 is simpler)

My setup:
Arch x86_64 newest.
Chromium from official repos, newest (Version 61.0.3163.79 (dev-build) (64-Bit))

![1](https://user-images.githubusercontent.com/26004708/30272152-627f8d04-96f3-11e7-943b-ebcf56b81c6a.jpg)
![2](https://user-images.githubusercontent.com/26004708/30272154-62a0822a-96f3-11e7-8bc4-ebc1b03456e4.jpg)
![3](https://user-images.githubusercontent.com/26004708/30272153-62802a84-96f3-11e7-802d-b6b421f9160a.jpg)
![4](https://user-images.githubusercontent.com/26004708/30272150-627ec81a-96f3-11e7-9181-d5b127221004.jpg)
![5](https://user-images.githubusercontent.com/26004708/30272151-627f1176-96f3-11e7-9bfd-d04220c48edf.jpg)

**Comment by PrestanceDesign** [comment] 2017-09-11 11:42
Duplicate of #2633

**Comment by mrmr1993** [comment] 2017-09-11 20:38
Looks like #2369 is responsible. Ping @gdh1995, it being your PR.

**Comment by gdh1995** [comment] 2017-09-12 01:28
Sorry, I'm testing it today.

**Comment by mrmr1993** [comment] 2017-09-12 10:15
I've pushed PR #2636, which should fix this.

**Closed** 2017-09-12 10:18 UTC

**Comment by Lazarus535** [comment] 2017-09-12 12:27
Just tested f3b186c0.
On my non-HiDPI screen, with --force-device-scale-factor=2 (the bug was also present there) the issue is fixed.
Will test on my HiDPI in about 6h.
Thanks you all! Great work!

**Comment by dkadashev** [comment] 2017-09-14 12:09
I run Chromium with --force-device-scale-factor=1.5. Before vimium was upgraded to 1.60 everything was fine. But after the upgrade today if the page is scrolled down then hints are at wrong positions.

I use chromium from the debian testing repo:

Chromium 60.0.3112.78 built on Debian buster/sid, running on Debian buster/sid

**Comment by dkadashev** [comment] 2017-09-14 13:51
Looks like 1.60.2 fixes the issue for me, thanks!
