### ISSUE TITLE
Vimium breaks "Remove" button on pay.google.com

### ISSUE THREAD

**Issue by ravron** [philc/vimium#3002] opened 2018-03-31 17:00 UTC
To reproduce this bug, you must have a Google account. Repro steps:

1. Ensure Vimium is installed and enabled.
1. Navigate to https://pay.google.com/send/paymentMethods?authuser=0.
1. If you have one or more payment methods already added, skip to step 3. Otherwise, add any valid payment method and return to https://pay.google.com/send/paymentMethods?authuser=0.
1. Choose one of your listed payment methods and click "Remove." 

Expected behavior: pay.google.com creates a pseudo-popup confirming you want to remove the payment method.
Observed behavior: nothing appears to happen. 

Disabling Vimium through its own settings — i.e. by adding an empty rule for play.google.com — doesn't fix the issue. Disabling it via chrome://extensions does, though.

- Chrome: 65.0.3325.181
- Vimium: 1.63

**Comment by smblott-github** [comment] 2018-04-01 06:40
This is probably a duplicate of #2997.

Assuming that that's correct, I'll close this and move the dicusssion over there.

**Closed by smblott-github** 2018-04-01 06:40 UTC

**Comment by ravron** [comment] 2018-04-01 17:27
@smblott-github ah, yep, that looks right. Thanks for finding that dupe!
