### ISSUE TITLE
Feature request: Close one tab to the left/right

### ISSUE THREAD

**Issue by tarek2** [philc/vimium#1843] opened 2015-09-27 15:16 UTC
It often happens you want to close only one tab to the left/right of the current tab. Can this be supported by Vimium?

**Comment by gdh1995** [comment] 2015-10-02 12:25
It's easy to write, and I've supported this function (also removed the old functions `closeTabsOnLeft`) in my project [Vimium++](/gdh1995/vimium-plus).

In fact, I think a command `closeTabOnLeft` accepting count as its index is better than `closeTabsOnLeft`.

**Comment by smblott-github** [comment] 2015-10-02 12:28
I've been wondering about this one (but forgot to post back).

The obvious thing to do is to add a count to the existing functions.  No count prefix: remove all relevant tabs; with count prefix: just remove that many tabs.

The problem is that we don't (currently) distinguish between no prefix and a prefix of `1` (and a prefix is `1` is likely to be the most common case).  Also, it's pretty undiscoverable.

**Comment by gdh1995** [comment] 2015-10-02 12:34
I add this: * `closeTabOnRight` will close the N-th tab to right of the current tab.

Then, a prefix of `1` means to close the next one tab only, but not the current one. It works well for me.

Use case: a page next to the current tab fails to load, and then if I active it, vimium will be disabled, but I just want to close it using Vimium.

**Comment by smblott-github** [comment] 2016-01-30 16:45
Closing.
Not clear how to resolve this effectively.

**Closed by smblott-github** 2016-01-30 16:45 UTC
