### ISSUE TITLE
Review and act on all existing PRs

### ISSUE THREAD

**Issue by maximbaz** [philc/vimium#1457] opened 2015-02-02 19:52 UTC
I know the main focus for the following release is to get implemented visual mode #1441.

For the subsequent release I propose to set the following goal: **reach the `zero pull requests` state**.

As of today, there are 60 opened pull requests, the oldest were opened back in 2013. Many of them (most?) don't seem to have any pending action, they are just forgotten. But what stroke me the most is the fact that it seems like *we lost track of existing attempts to improve the product*. 

Being honest, I haven't gone through the entire list. I picked a few, had a quick glance, and what I saw:

* Visual mode #1441, now being implemented by @smblott-github, was first attempted in #1018, then in #1281.
* Different language inputs, discussed in #1387, was already attempted in #801.
* Having an indicator of the current mode was initially proposed back in #1088.

And I'm not even saying a word about gazillion of opened pull requests, made by @mrmr1993.

I'd like to underline, I'm not arguing to blindly merge all existing PR. But let's pick a time (for example after the next release with visual mode), stop implementing new features and revise all proposed PRs. We should express our concerns in the PRs (if any), give authors a time limit to react (or take over the code), and close everything that is irrelevant anymore.

Ideal state in my opinion would be reaching zero pull requests, and trying to preserve that state in future.

As a positive co-product of taking care of the PRs list, after we cleanup there we will bring quite a few shiny features to vimium :+1: 

P.S. I'd also like to go through all opened issues, we have some opened since 2010 and I'm sure many of them are duplicates or invalid as of today. But starting with PRs seems more reasonable to me.

P.P.S. Related: #1173

/cc @philc, @smblott-github, @mrmr1993

**Comment by mrmr1993** [comment] 2015-02-02 22:24
> For the subsequent release I propose to set the following goal: **reach the `zero pull requests` state**.

I'm going to disagree: I think we should create issues for the open PRs that don't have them, and then focus on issues.

I want to suggest working through the open issues, tagging each one with `fixed`, `invalid`, `waiting`, `duplicate of #blah`, `blocking #blah`, `priority-X`, `PRs open`, etc. and *then* looking at the PRs that fix them where applicable. We should aspire to "zero pull requests" as a consequence of there being no issues, not that a few people can check and merge code more quickly than other people are writing it. We also include more users in discussions if we have them on issues, which surely isn't a bad thing.

This way of working also forces us to discuss properly before writing code, so that we know what we're expecting from the PR, and don't make changes without discussion. An example still painfully fresh in my mind is #1406 and #1413:
* there was no decided specification for how modes should look/behave, so nothing to compare the code to
* the PRs weren't limited by the scope of an issue or the combination of issues
  - this meant that decentralised code flow and modes in the icon were 'carried along for the ride', without much separate discussion on their merits. (I still strongly disagree with the code flow change.)
* none of the requesters of visual mode had any way of knowing that the discussion was related, and so couldn't have any input on the changes

> I'm not even saying a word about gazillion of opened pull requests, made by @mrmr1993.

I'll go and make a cull now. Still, a lot of those PRs fix issues. If we systematically work through open issues, we'll gain a lot of clarity about what people want from the project *and* be able to discuss ideas properly; PRs are just a tool for moving the implementations of ideas into the codebase.

**Comment by z0rch** [comment] 2015-02-02 23:05
> I want to suggest working through the open issues, tagging each one with fixed, invalid, waiting, duplicate of #blah, blocking #blah, priority-X, PRs open, etc. and then looking at the PRs that fix them where applicable.

Obviously that would be even better. The reasoning I have behind starting from PRs is only to bring some granularity to this effort (we have 250 issues vs 60 PRs). Plus -- yes, most PRs are linked to issues, so we will not loose the context completely. But if that is OK with others to start looking through issues instead, let's go this way!

One question I want to clarify for myself: what notion of `active` github issue do we use here? Is it "the fix is not ready yet", or more like "up until the issue author has agreed with our solution and verified it"? So in the first case we immediately close issues marked as "invalid" or "duplicate" (or as soon as the fix has been merged into `master`), but in the second case we keep them opened until authors agree and close their issues themselves.

**Comment by mrmr1993** [comment] 2015-02-02 23:17
> what notion of `active` github issue do we use here?

I would:
* mark as 'fixed' (or 'waiting for feedback', as appropriate)
* leave open (since the author can close issues but not reopen ones we close, we don't really more duplicate issues)
* close 'fixed' issues that haven't been updated in (say) 1 month

**Comment by z0rch** [comment] 2015-02-02 23:19
> since the author cannot reopen (issues) we close

Wow, that is news to me. Then I agree.

**Closed** 2016-01-30 15:54 UTC
