### ISSUE TITLE
keyIdentifer is deprecated

### ISSUE THREAD

**Issue by codyhess** [philc/vimium#2293] opened 2016-10-03 20:13 UTC
'''
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
'''

I caught this error in my Dev Tools. I imagine it's an easy (one line) fix. Making a PR soon.

MDN for the deprecated [KeyboardEvent.keyIdentifier](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier), and it's replacement [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key).

**Comment by codyhess** [comment] 2016-10-03 20:19
Never mind on the PR -- KeyboardEvent.key returns a printable character instead of a unicode string, so more refactoring is necessary.

**Comment by innaterebel** [comment] 2016-10-04 00:08
Duplicate of #2288.

**Closed** 2016-10-04 04:43 UTC
