### ISSUE TITLE
Recent tabs not listed on pressing 'T' in Edge. '^' also does not move to the previous tab

### ISSUE THREAD

**Issue by odiyan** [philc/vimium#4421] opened 2024-02-11 12:52 UTC
**Describe the bug**

Edge ~~with multiple windows.~~ (Confirmed this behavior on a single window as well.) I use 'T' to navigate between tabs, and the list used to be the most recently accessed tabs. This is no longer the case. Also related, pressing '^' doesn't take me to the last tab I accessed. This issue started happening around December 2023.

**To Reproduce**

1. Open a window on edge with a few 100 tabs
2. Try accessing different tabs.
3. Try to see the list of recently used tabs by pressing 'T'
4. Check if '^' takes you to the last visited tab.

**Browser and Vimium version**

Edge version - 121.0.2277.112 (Official build) (64-bit) 
Vimium version - 2.0.5

**Comment by philc** [comment] 2024-03-02 21:22
This is a duplicate of #4326, which has been fixed. This fix will be in the next release of Vimium, in a few weks.

**Closed by philc** 2024-03-02 21:22 UTC
