### ISSUE TITLE
Vimium-FF FindMode gets stuck on first couple of letters

### ISSUE THREAD

**Issue by adrianord** [philc/vimium#3807] opened 2021-04-24 06:43 UTC
**Describe the bug**
In Vimium-FF, the FindMode used after pressing `/` will often times get stuck while typing, usually getting stuck on the first letter but sometimes getting stuck after a couple of letters. Clicking around or tabbing around the webpage sometimes fixes it but not always. This is even with Quick Find in Firefox turned completely off in the about:config.

**To Reproduce**
1. Go to URL 'https://github.com/awesome-streamers/awesome-streamerrc/blob/master/TheAltF4Stream/init.vim'
2. Enter FindMode using `/`
3. Try typing "Plug"
4. What FindMode not get past "P"

**Browser and Vimium version**
Name 	Firefox
Version 	87.0
Build ID 	20210318103112
Distribution ID 	canonical
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
OS 	Linux 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2

Pop OS 20.04
Vimium-FF version 1.66

**Comment by gdh1995** [comment] 2021-04-24 13:25
A duplicate of ##3774

**Closed** 2021-04-26 01:00 UTC
