### ISSUE TITLE
CJK IME problem on OSX

### ISSUE THREAD

**Issue by cissusnar** [philc/vimium#2858] opened 2017-12-08 09:38 UTC
[wrong.mov.zip](https://github.com/philc/vimium/files/1542158/wrong.mov.zip)

using CJK IME will lose focus when press ESC, and leave some wrong letters at text input field. 

(all platform)

**Comment by mrmr1993** [comment] 2017-12-08 10:34
This sounds like a duplicate of #2768.

**Closed** 2019-09-19 14:19 UTC
