### ISSUE TITLE
Can't scroll comments in Reddit

### ISSUE THREAD

**Issue by WovenTide** [philc/vimium#3477] opened 2020-01-24 10:21 UTC
Hello,

When I open comments in Reddit, I can't scroll them with the J and K keys. It's the only website I have issues with.

I'm on Firefox 72.0.2 on Linux and Vimium version is 1.64.6.

I've seen that this issue was reported before but it was supposed to be fixed. I'm not used to Github so I'm not sure If I was supposed to open a new issue for this.

Let me know if you need anymore information !

**Comment by gdh1995** [comment] 2020-01-24 13:04
Um, not reproduced on Firefox 72.0.1 + Windows 10 x64 + Vimium (master)

**Comment by WovenTide** [comment] 2020-01-28 13:29
I have the same problem on Brave Version 1.2.43.
Maybe it's an issue with Linux ?

If you need me to test anything, let me know.

**Comment by gdh1995** [comment] 2020-01-29 04:07
Sorry I wasn't testing on Vimium C v1.64.6. Then this is a duplicate of #3119 and has been fixed by #3327 .

@philc Maybe a new patch version of Vimium can be published firstly, ignoring unmerged PRs and issues.

**Comment by philc** [comment] 2020-02-08 20:26
This is fixed in master and will be released to the store in the next 1-2 days.

**Closed by philc** 2020-02-08 20:26 UTC
