### ISSUE TITLE
Yank doesn't work in Vivaldi

### ISSUE THREAD

**Issue by mehrad-m** [philc/vimium#2864] opened 2017-12-12 09:28 UTC
Recently when I yank I see the vimium tooltip at the bottom but I get nothing on my clipboard.
vimium:  1.62

**Comment by smblott-github** [comment] 2017-12-12 10:01
Are there any errors is the console?

**Comment by mehrad-m** [comment] 2017-12-12 13:30
Background page console:
chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/logging.html
2_generated_background_page.html:1 Error in event handler for webNavigation.onCommitted: Error: Invalid value for argument 1. Value must not be less than 0.
    at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/background_scripts/main.js:544:24

also when I press yy or yf in vimium setting or vimium logging, it works fine

**Comment by smblott-github** [comment] 2017-12-12 13:34
That code hasn't changed for a long time.  But that's on the background page.  What about the content script (so, the regular JS console)?

**Comment by mehrad-m** [comment] 2017-12-12 13:43
If you mean the console for web pages, no

**Comment by mehrad-m** [comment] 2017-12-12 13:45
If you mean the console for web pages, there is no error for vimium

**Comment by mickesv** [comment] 2017-12-14 09:40
vimium v1.62.2, Vivaldi version 1.13.1008.36 on OSX here. I did some looking around, and notice that in `manifest.json`, "permissions" only include "clipboardRead" but not "clipboardWrite" (It also includes a weird "\u003Call_urls>" at the end, but that's probably unrelated).

In order to troubleshoot, I tried adding "clipboardWrite" but that did not help. Is there someplace else that should also be updated?

(for full reference, the manifest.json file I found was under `~/Library/Application Support/Vivaldi/Default/Extensions/dbepggeogbaibhgnhhndojpepiihcmeb/1.62.2_0` )

**Comment by smblott-github** [comment] 2017-12-14 10:17
#2867 might be related.  Probably the source of the problem is #2601.

**Comment by smblott-github** [comment] 2017-12-14 11:05
> In order to troubleshoot, I tried adding "clipboardWrite" but that did not help. Is there someplace else that should also be updated?

`clipboardWrite` is needed in FF but not in Chrome.  It's stripped from the manifest when the Chrome package is being built; [here](https://github.com/philc/vimium/blob/master/Cakefile#L82).

**Comment by mickesv** [comment] 2017-12-14 12:16
Yeah, I know. It was a longshot, based on https://developer.chrome.com/extensions/declare_permissions and that things seem to have broken right around the time of the #2852 merge.

**Comment by paul** [comment] 2017-12-22 04:41
I am also experiencing this problem. Is there a resolution yet, or do I need to wait for #2601 to be merged?

**Comment by smblott-github** [comment] 2017-12-22 07:17
#2601 is already merged and released (and is probably the source of the problem for Vivaldi users).

I can reproduce this bug in that yank works, but only if the `clipboardWrite` permission is in the manifest; otherwise, yank does not work.

The Chrome Store version *does not* have the `clipboardWrite` permission (because Chrome does not need it).  The Firefox version *does* have the `clipboardWrite` permission.

I'm not too keen to add the `clipboardWrite` permission for the Chrome Store version, because that instantly disables Vimium for all of our Chrome users.

**Comment by gdh1995** [comment] 2017-12-22 08:37
> I can reproduce this bug in that yank works, but only if the clipboardWrite permission is in the manifest; otherwise, yank does not work.

@smblott-github Sorry to bother you but my English is too poor to understand this sentence. What Vivaldi does if Vimium has the `clipboardWrite` permission?

**Comment by smblott-github** [comment] 2017-12-22 08:39
> What Vivaldi does if Vimium has the clipboardWrite permission?

Yank works correctly for me.

However, @mickesv reports the opposite, above.

**Comment by gdh1995** [comment] 2017-12-22 14:08
> Yank works correctly for me.

Thanks.

And on my tests just now, `yank` works correctly on an incognito `file:///e:/` tab if Vimium has `clipboardWrite`. My test environment is Chrome 63.0.3239.108 x64 (stable) on Windows 10 creator.

**Comment by rangercej** [comment] 2018-01-16 15:51
_Vivaldi 1.13.1008.32, Vimium 1.62.4_

Having the same issue. I've added clipboardWrite to manifest.json in %LOCALAPPDATA%\Vivaldi\User Data\Default\Extensions\dbepggeogbaibhgnhhndojpepiihcmeb\1.62.4_0

The console at chrome-extension://dbepggeogbaibhgnhhndojpepiihcmeb/pages/logging.html has:

```
15:44:33.858: 0 handle key y (normal)
15:44:34.050: 0 handle key y (normal)
15:44:34.051: 0   invoke copyCurrentUrl count=1 
```
I do get the tool-tip but the URL isn't on the clipboard. 

For those that have got it working by modifying the manifest, is anything more needed beyond restarting Vivaldi? Or does the edit need to be done before installing the extension?

**Comment by apricant** [comment] 2018-01-28 21:09
finding the same issue as above, I have added clipboardWrite to permissions in `manifest.json` located in `/home/user/.config/vivaldi/Default/dbepggeogbaibhgnhhndojpepiihcmeb/1.62.4_0`

Permissions are as follows:
`"permissions": [ "tabs", "bookmarks", "history", "clipboardRead", "clipboardWrite" "storage", "sessions", "notifications", "webNavigation", "\u003Call_urls>" ],`

Tooltip functional for me as well, and the URL is also not in clipboard.

Just providing additional information in hopes for a solution.

**Comment by mehrad-m** [comment] 2018-03-26 14:20
For anyone having this issue, I now use vimium + cVim to have yank work in vivaldi and I've added this to my cVim setting.

`unmapAll`
`map yf yankUrl`
`map yy yankDocumentUrl`

**Comment by mehrad-m** [comment] 2018-03-26 16:08
For anyone having this issue, I now use vimium + cVim to have yank work in vivaldi and I've added this my vimium and cVim setting.
vimium
`map y enterInsertMode`
cVim
`unmapAll`
`map yf yankUrl`
`map yy yankDocumentUrl`

**Comment by xoihiox** [comment] 2018-10-23 22:19
@mickesv, it has been awhile, but are you still having the same problem with pasting from the clipboard in vivaldi with vimium?

After changing the permissions, you need to load the unpacked extension for them to take effect.  You can do this by enabling chrome developer options and selecting "Load Unpacked" from the extensions menu.  I believe you can load the extension from the exact same location it was originally in.  A red icon will appear next to the vimium icon that says "Unpacked Extension".  After that, you should be good to go.

Note:  I arrived at this solution via trial and error, so I may not be doing it 'right'--that is, the words 'packed' vs. 'unpacked' mean nothing to me.

**Comment by mickesv** [comment] 2018-10-24 06:36
@xoihiox Your suggestion seems to have done the trick. Thank you!

STEPS:
1. Edit the file `~/Library/Application Support/Vivaldi/Default/Extensions/dbepggeogbaibhgnhhndojpepiihcmeb/1.64_0/manifest.json`
 (or whichever version you are running; the detailed path may vary)
2. Find the line that reads `"permissions":` and add `"ClipboardWrite"` to the array.
3. Open the URL `chrome://extensions`
4. toggle the "Developer Mode" slide
5. Select "Load Unpacked" and point it towards `~/Library/Application Support/Vivaldi/Default/Extensions/dbepggeogbaibhgnhhndojpepiihcmeb/1.64_0`
6. ...
7. Profit!

**Comment by mehrad-m** [comment] 2018-11-02 10:54
This problem has solved in recent version of vivaldi

**Closed** 2018-11-02 10:54 UTC

**Comment by rangercej** [comment] 2018-11-08 14:43
Confirmed for me -- it looks like it's the latest release (2.1.1337.36) that resolved it.
