### ISSUE TITLE
Bug: Smooth scrolling fails when privacy.resistFingerprinting is set to true (Firefox)

### ISSUE THREAD

**Issue by demoknight-tf2-lol** [philc/vimium#3759] opened 2021-01-28 12:50 UTC
I have tested this on Firefox 85.0 and LibreWolf 84.0.1 on Arch Linux

Steps to reproduce: set `privacy.resistFingerprinting` to `true` in `about:config`.
Smooth scrolling fails to function correctly.

**Comment by gdh1995** [comment] 2021-01-28 15:05
A duplicate of #3641, and #3701 may fix this (though I think the PR still has some new issues).

**Comment by kaimyel** [comment] 2022-05-27 09:25
This issue is still persists.

**Comment by philc** [comment] 2023-09-17 03:43
Closing in favor of #3641.

**Closed by philc** 2023-09-17 03:43 UTC
