### ISSUE TITLE
LinkHints.activateModeToOpenInNewForegroundTab opening tabs twice

### ISSUE THREAD

**Issue by LawranceFung** [philc/vimium#3986] opened 2022-01-14 18:10 UTC
LinkHints.activateModeToOpenInNewForegroundTab opens tabs twice, whether I have custom mappings or not.  
I tried disabling all other plugins to no avail.  This issue is happening with my other computers, so it might be a problem with my account.

**Comment by imbrucy** [comment] 2022-01-14 19:37
I'm having the same issue, so it's not specific to your account. Just started today.

**Comment by LawranceFung** [comment] 2022-01-14 20:58
It was 2-3 days ago for me.  It might have to do with the newest version of firefox?

**Comment by gdh1995** [comment] 2022-01-15 02:01
Duplicate of #3964 .

**Comment by freefal** [comment] 2022-01-19 22:40
Confirming that I am experiencing this same issue.

**Closed** 2022-01-20 04:37 UTC
