### ISSUE TITLE
PageUp/PageDown not using scrollFullPage<type> and not mapable?

### ISSUE THREAD

**Issue by Thiana** [philc/vimium#1915] opened 2015-12-19 21:35 UTC
Using Vimium 1.53 and Chrome 47.0.2526.106 the PageUp/Down keys arent scrolling a full page. 

If you map Space to scrollFullPageDown, then just alternate Space/PageUp you'll see that it's not returning  to the same point in the page. You end up at the bottom of the document after a while.

Attempting to unmap &lt;PageDown&gt; and map &lt;PageDown&gt; scrollFullPageDown still doesnt do a full page scroll.

Any ideas? Thanks.

**Comment by smblott-github** [comment] 2015-12-20 07:02
Chrome's native page-scrolls scroll slightly less than full page.  Vimium's don't.  I guess we could change that.

Vimium does not support mapping of `PageUp/Down`.  So, in your example, you're mixing Chrome and Vimium movements.

**Comment by Thiana** [comment] 2015-12-20 07:47
Thats unfortunate :( 

You may want to update the Command Listing on the options page then because it specifically lists PgUp/Down as mapped to scrollFullPage* instead of the chrome default.

Having an option to allow a full page scroll with PgUp/PgDown would be nice. It's awkward having the  partial scroll when every other program does a full screen. Thanks.

**Comment by smblott-github** [comment] 2016-01-30 12:23
Closing.
I think the status quo is the intended behaviour.

**Closed by smblott-github** 2016-01-30 12:23 UTC
