### ISSUE TITLE
yy shortcut is not working

### ISSUE THREAD

**Issue by Huray-hub** [philc/vimium#4173] opened 2022-11-17 08:55 UTC
The yy shortcut shows the popup "yanked <url>" but when I paste there is nothing on the clipboard

1. go to any URL
2. press yy
3. paste wherever you want

Vimium: 1.67.2

Browser: 
Brave 1.45.127, Chromium: 107.0.5304.110 (Official Build) (64-bit)

OS: 
1. Arch Linux
2. Windows 11 Version 22H2 (Build 22621.819)

**Comment by jwilkeson** [comment] 2022-11-18 17:35
Related to https://github.com/philc/vimium/issues/4149

**Comment by mb720** [comment] 2022-11-22 20:11
The issue I'm seeing is that although yanking the current URL works for HTTPS sites, it doesn't for HTTP (non-encrypted) sites. The debugger shows this after pressing `yy` on an HTTP site:

    Uncaught (in promise) TypeError: navigator.clipboard is undefined
        copy moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/lib/clipboard.js:18
        copyToClipboard moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:147
        setTimeout handler*setTimeout moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/lib/utils.js:278
        copyToClipboard moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:145
        <anonymous> moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:174
        onmessage moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/ui_component_server.js:23
        portOpen moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/ui_component_server.js:21
        registerPort moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/ui_component_server.js:9

I did not encounter the symptoms described [here](https://github.com/philc/vimium/issues/4149): blurring and losing focus.

Vimium 1.67.3, Mozilla Firefox 107.0, Arch Linux 6.0.8.

Thanks for Vimium, it's awesome!

**Comment by gdh1995** [comment] 2022-11-23 01:59
`navigator.clipboard is undefined` has been reproduced on Firefox 106 for Windows x64, but not on Chrome 107.

So, I think it's a bug of Firefox - Chrome or Firefox tends to apply too strict limits on web-extensions unless too many developers "dare to" leave them.

**Comment by cheecheeo** [comment] 2022-11-27 01:13
i'm also reproducing this issue on windows with brave browser.

**Comment by mb720** [comment] 2022-12-03 11:42
Using Vimium 1.67.4 on Firefox 107.0.1, I noticed that yanking the URL from HTTPS sites stopped working as well:

    Uncaught (in promise) DOMException: Clipboard write was blocked due to lack of user activation. 2 clipboard.js:18
        copyToClipboard moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:151
        AsyncFunctionThrow self-hosted:811
        (Async: async)
        setTimeout moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/lib/utils.js:278
        copyToClipboard moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:145
        <anonymous> moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/hud.js:174
        onmessage moz-extension://3c472571-c4dd-455e-81b3-f282ddd0880b/pages/ui_component_server.js:23

The error on HTTP sites is still:

    Uncaught (in promise) TypeError: navigator.clipboard is undefined

**Comment by WilliamWelsh** [comment] 2022-12-04 18:54
I'm on the same version, also on FireFox, and get the same exact error message. `clipboardWrite` is missing from [manifest.json](https://github.com/philc/vimium/blob/master/manifest.json) under permissions. I think they might have removed it cause Chrome doesn't need it anymore or something, but it is still needed for FireFox. For what it's worth, doesn't work on chrome either.

**Comment by mcp292** [comment] 2022-12-05 21:23
Possibly related to: https://github.com/philc/vimium/pull/4122.

Source: https://github.com/philc/vimium/commit/9aa3b2b022329c05af8a6e0bb79bac916d316c51#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3.

**Comment by WnP** [comment] 2022-12-07 09:24
I can confirm that all clipboard operations (like `yy` and `yf`) no longer works since `1.67.4` on Firefox due to:
```
DOMException: Clipboard write was blocked due to lack of user activation.
```
Please rollback https://github.com/philc/vimium/commit/15ba534fc8eda6ed72d641e0002d00d6d255e1d0 :pray:

**Comment by citosid** [comment] 2022-12-15 14:32
I've added this MR https://github.com/philc/vimium/pull/4186 but hasn't been merged. Once it does and there is a new release should be fixed

**Comment by philc** [comment] 2022-12-17 23:38
Now that #4186 is merged, this should be fixed. v1.67.5 has been submitted to the firefox addons site.

**Closed by philc** 2022-12-17 23:38 UTC

**Comment by AetherUnbound** [comment] 2022-12-18 04:16
Thank you!

**Comment by cheecheeo** [comment] 2023-01-09 22:56
@philc could v.1.67.5 also be submitted to the chrome addons site?

**Comment by philc** [comment] 2023-01-09 23:13
Hey @cheecheeo, what's the rationale? v1.65.5 and v1.65.6 have changes that only apply to Firefox, so I didn't bother going through the Chrome approval process for them.

**Comment by cheecheeo** [comment] 2023-01-09 23:18
@philc oh ok. if these changes won't fix chromium or brave then no rationale, I was hoping this fix would also fix brave and chromium. if i'm reading correctly that was the original bug report.

**Comment by citosid** [comment] 2023-01-10 12:42
> @philc oh ok. if these changes won't fix chromium or brave then no rationale, I was hoping this fix would also fix brave and chromium. if i'm reading correctly that was the original bug report.

I think one of the comments mentions this issue was related to #4149 and as can be seen in [this comment](https://github.com/philc/vimium/issues/4149#issuecomment-1356882919) it was already fixed. 

I think the confusion came since [this comment](https://github.com/philc/vimium/issues/4173#issuecomment-1324186296) in this issue talked about Firefox and then we began using it for Firefox only

**Comment by cheecheeo** [comment] 2023-01-10 20:33
@citosid thank you for the information! i subscribed over to #4200 as that seems to encapsulate the behavior i'm experiencing well.

**Comment by mcp292** [comment] 2023-03-03 21:58
> I think this problem re-surfaced.
> 
> I am on Firefox 110.0 for Arch Linux using Vimium 1.67.6.

Not sure why or what caused this, but I'm still on 1.67.6 and this works. I have updated my browser since.

Apologies for any confusion caused. Safe to ignore.
