### ISSUE TITLE
Escape doesn't behave like it used to on some sites

### ISSUE THREAD

**Issue by tranquochoan** [philc/vimium#4354] opened 2023-10-31 03:00 UTC
So it used to be like this: when I finish typing in some boxes for text (search box, comment box, etc.), press ESC would get me out of that box and I could navigate the page using j,k,u,d again. 

But for the past several days, pressing Esc doesn't get me out, and when I press u, d to navigate the page, the letters are attached to the text I typed in the text box.

Firefox version 118.0.2 (64-bit)
Ubuntu 22.04.2 LTS (64-bit)
Vimium 2.0.4

**Comment by tranquochoan** [comment] 2023-10-31 05:07
Oh and I've just found that it only happens when I open another private window simultaneously, and it happens on both private and normal windows once there is a private window

**Comment by tvale** [comment] 2023-10-31 08:00
I was also experiencing the issue where pressing escape would not get me out of the input element, regardless of whether I had a private window open or not.

> Oh and I've just found that it only happens when I open another private window simultaneously, and it happens on both private and normal windows once there is a private window

Based on this observation I turned off the _"Run in Private Windows"_ option for Vimium [1] and escape started working like it did.
Hopefully it will also work for you as a temporary workaround.

Presumably this means that the issue is somehow related to private windows.

[1] about:addons -> Vimium -> Run in Private Windows -> Don't Allow

**Comment by Inkrementator** [comment] 2023-10-31 22:05
It also happens to me, and I don't use private windows.

**Comment by tranquochoan** [comment] 2023-11-01 00:57
I turned off the Run in Private Windows and it seems to work fine now. The thing is it was working well several days ago even with that option on. 
@Inkrementator Do you have that option on? You could try turning it off, it seems to work for me

**Comment by tranquochoan** [comment] 2023-11-01 01:19
I just roll back to the previous version and so satisfied.  Here is the version history page https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org

**Comment by jtmr05** [comment] 2023-11-03 14:23
I've been experiencing this problem as well on Firefox 119, Vimium version 2.0.4

**Comment by philc** [comment] 2023-11-07 01:41
Hey folks, I believe this is a duplicate of #4336 and I believe it is fixed in by dca6ca7a9a2404c7ccbba2184b35cbca563cf0d5. I'm going to release v2.0.5 tonight. Please let me know if you encounter this with the latest Vimium release.

Any write to session.storage would trigger this bug for all open tabs. I believe this issue *does* in fact occur more often when using private windows, because each time Vimium's find mode is used in an incognito/private window, it writes to session.storage.

**Closed by philc** 2023-11-07 01:41 UTC
