### ISSUE TITLE
omnibar doesn't use browser's preferred search engine by default

### ISSUE THREAD

**Issue by 2gn** [philc/vimium#4442] opened 2024-03-22 09:25 UTC
**Describe the bug**
It might not actually be a bug but a feature, vimium does not use browser's preferred search engine by default, when trying to search from omnibar. I expected it to use DuckDuckGo (my preferred search engine) as its search engine, but it opened Google instead. I know this can be altered from settings, but I thought defaulting to browser's settings would be better.

**To Reproduce**

1. press "o" to open the omnibar
2. input query and press Enter.

**Comment by philg-dev** [comment] 2024-03-28 03:25
The Vimium options let you set your "default search engine" for the vomnibar.

It defaults to google due to the way it's implemented. I'm not entirely sure if the add-on can read the browser's configuration for the default search engine explicitly.

According to MDN the [`API method browser.search.search()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search/search) would use the browser's default search engine.

However, this API is only supported by Firefox desktop, as you can see from the compatibility table in the link above.

Since chrome does not offer this search API, there's no way to implement a simple solution that works uniformly across browsers.

This is also stated in [this code comment in `url.utils.js`](https://github.com/philc/vimium/blob/75513dec05579efd5dd77a52397152c1b93a4646/lib/url_utils.js#L128)

So I guess for the time being, the best solution is to just change the provided option in Vimium and set the Vomnibar's default search engine to your liking, independently from your browser's default search engine.

> (Disclaimer: I've noticed that the author of the add-on has a similar name as I do. I'm not the same person - I'm a very new user of Vimium and was just looking into things.)

**Comment by philc** [comment] 2024-03-28 03:55
@philg-dev We do have the API we need (search.query). See #4439.

Closing this as a dupe of #2598.

**Closed by philc** 2024-03-28 03:55 UTC
