### ISSUE TITLE
search URL with %S opens in google instead of directly

### ISSUE THREAD

**Issue by tkossak** [philc/vimium#4381] opened 2023-11-30 16:53 UTC
**Describe the bug**

I have this search configured: `gg: https://www.google.com/search?q=%S` and when I search for phrase containing space eg `aa bb`, instead of searching google for `aa bb` it searches google for url `https://www.google.com/search?q=aa bb`.

**To Reproduce**

1. Go to vimium settings
2. In custom search engines add this line:
`gg: https://www.google.com/search?q=%S`
3. Save changes
4. Go to any page and press `o` and enter `gg aa bb`.
5. See that google page opens with `https://www.google.com/search?q=aa bb` as query string, instead of `aa bb`.

![google_search](https://github.com/philc/vimium/assets/3728245/00f33ae0-c21b-479a-8dc0-d4f023ba48cd)

**Browser and Vimium version**
- Firefox 120.0 (64-bit)
  - build ID: 20231120231815
  - Distribution ID: Manjaro
- Vimium 2.0.6

**Comment by astr0n0mer** [comment] 2024-01-06 11:47
There's a typo in your rule
Use this:
(notice lowercase `s` at the end)
```markdown
gg: https://www.google.com/search?q=%s
```

**Comment by tkossak** [comment] 2024-01-07 12:56
no, `%S` is another correct placeholder and it means something different (term won't be URI encoded, while `%s` encodes it)

**Comment by astr0n0mer** [comment] 2024-01-09 06:59
Hey, I didn't know that, thanks for introducing me to this new format specifier

I added this rule `gg: https://www.google.com/search?q=%S` and observed that if you use `+` instead of a `space` in your query, it will search correctly on Google

To reproduce:
1. Go to any page and press `o` and enter `gg aa+bb`.
1. See that Google page opens with `aa bb` as the search query

Explanation:
I believe since we're not encoding anything with `%S`, adding a `space` makes Vimium think that all the text is a search query `https://www.google.com/search?q=aa bb`
But when we use `+`, Vimium can correctly interpret it as a URL

**Comment by tkossak** [comment] 2024-01-09 16:06
Seach for `a+b` with `%S` is the same as search for `a b` with `%s` (url ends up having `a+b` in both cases). Google is not a problem here, because it works fine with `%s`, but I had website that didn't work with searching for `a b` because it was encoded in url (by vimium adding `+` in between) and the website didn't handle it properly. `%S` should pass values with spaces as they are (without any encoding) and not searching whole url in google. It seems like a bug.

It's not that important for me anymore, because lately the site started working with `+` in urls (probably they updated it), so I can use `%s`, but somebody else may have similar problem.

**Comment by philc** [comment] 2024-01-11 05:05
I think the original annoyance here was that Vimium encodes spaces in URLs as `+` rather than `%20`, and the site in question didn't properly recognize `+` as a space character. That's been fixed in #4401.

The other issue @tkossak described is that using %S can result in an invalid URL, and Vimium will treat it as a search query rather than try to navigate to it.

I agree that this is probably a bug, but I think a minor one, and some I'm closing as wontfix (fixing this would be involved). A URL with unescaped spaces is not a valid URL. Chrome for instance will encode the spaces with `%20`, even though they're shown as spaces in the URL bar. If you want to ensure the result of the custom search engine query is always a valid URL, use `%s`.

**Closed by philc** 2024-01-11 05:05 UTC

**Comment by tkossak** [comment] 2024-01-11 13:08
I can't check it anymore but I think that `%20` should solve this problem with `%s`, so thank you.
