### ISSUE TITLE
Input stolen on second character of Dart app

### ISSUE THREAD

**Issue by niedzielski** [philc/vimium#1684] opened 2015-05-26 03:16 UTC
1. Visit https://polymer-topeka.appspot.com/
1. Start entering your first name.
1. Observe that input is stolen starting with the second letter.

Vimium 1.51
Chromium 43.0.2357.65 (Developer Build) Built on Ubuntu 14.04, running on LinuxMint 17.1 (64-bit)

**Comment by smblott-github** [comment] 2015-05-26 04:43
Thanks @niedzielski.  Can reproduce this in 1.51.

Looks like it's already fixed in master by #1627 (thanks to @mrmr1993), f35341f42db93b5fde6712c2bc4bb767f5b9cc07.

**Closed by smblott-github** 2015-05-26 04:43 UTC
