### ISSUE TITLE
find mode accepts only one char

### ISSUE THREAD

**Issue by Abraxas-Knister** [philc/vimium#3796] opened 2021-03-27 19:55 UTC
**What happens**
I type `/` to enter find mode, type one character, it scrolls to the first match, highlights it and prints the pattern (so far) and how many matches are found (everything expected until here), I type further characters but the search pattern does't update. Find mode isn't exited automatically at that point, ie keys don't do what they do in normal mode. It appears they are captured by find mode but don't go to the pattern. I can then use Esc to exit find mode as expected.

![search](https://user-images.githubusercontent.com/43271791/112733134-734b6f80-8f3e-11eb-9b3a-9b2e0b0974ae.png)

**Browser and Vimium version**
vimium 1.66 on Firefox 86.0.1 (64-Bit) Linux 5.4.0-66-generic Ubuntu

**Comment by MRAAGH** [comment] 2021-03-28 23:36
duplicate of #3774

**Closed** 2021-07-10 04:28 UTC
