### ISSUE TITLE
weird scrolling behaviour

### ISSUE THREAD

**Issue by mohitleo9** [philc/vimium#1744] opened 2015-06-19 15:16 UTC
Hey,
I am experiencing some weird scrolling behaviour when using u or d (it doesn't stop, I have to hit escape to make it stop).
Steps to reproduce.
-> hit f to make hints visible.
-> open any one using ctrl and hint
-> go back to the previous page using H
-> scroll using u or d, it would not stop now.
On master 53e84b4800040fd573c7dce4493eb878ceb93766

**Comment by smblott-github** [comment] 2015-06-19 16:26
Hmm.  I can't reproduce it, but it's possible.  We continue scrolling until we see the relevant `keyup` event.  If there's a combination of modes and tab switches that causes us to miss it, then we continue scrolling indefinitely.

(However, I'm seeing another (separate) problem.  The `Ctrl` modifier doesn't work at all since we moved to `keypress`.  I don't have time to look into it now.  Will do soon.)

**Comment by mohitleo9** [comment] 2015-06-19 16:28
It's not a big deal, I just happened to find it, so no worries!

**Comment by mnechaev** [comment] 2016-01-12 07:13
Another strange bug:
1) Open any page
2) Press f to make hints visible
3) Type a hint in uppercase using Shift (like FA), a new tab opens
4) Keep pressing Shift, switch to the new tab (Shift + K)
5) Close new tab (x)
6) Press j or k. Scrolling won't stop until you refresh page.

**Comment by smblott-github** [comment] 2016-01-12 07:24
Thanks @mnechaev.  I think we got that fixed just a couple of days ago (#1930).  It'll be fixed in the next release.

(Closing this.)

**Closed by smblott-github** 2016-01-12 07:24 UTC
