### ISSUE TITLE
If i use mouse to select text， click again text, It won't be deselected .

### ISSUE THREAD

**Issue by suxb201** [philc/vimium#2725] opened 2017-10-15 11:17 UTC
Chrome 61.03

**Comment by smblott-github** [comment] 2017-10-15 11:22
Duplicate of #2527.

Unfortunately, nobody has figured out what's causing the problem.

(Will close this one issue.  You might want to subscribe to #2527.)

**Closed by smblott-github** 2017-10-15 11:22 UTC
