### ISSUE TITLE
Press F or f shows links but cannot navigate

### ISSUE THREAD

**Issue by tayk045** [philc/vimium#1783] opened 2015-07-29 16:46 UTC
Hi Vimium crew,

As shown in the picture below, when pressed PA or GA, Vimium does not navigate to the link; however, other link in the page seem to work just fine though. Not sure whether this is the problem for Vimium or not.

The problem link: http://www.timeout.com/newyork/movies/the-100-best-movies-of-all-time
Chrome version: 44.0.2403.107 m
Vimium version: 1.51

Thank you very much and love your product!

![capture](https://cloud.githubusercontent.com/assets/13112458/8963579/1779e792-364b-11e5-895d-831972d9d3a3.PNG)

**Comment by mrmr1993** [comment] 2015-07-30 02:11
Thanks for the bug report!

This page uses an interesting approach for these 'buttons'; they are `<label>` elements whose `for` attribute relates them to radio buttons (`<input type="radio">`). We're actually detecting the containing `<div>` element, because its `class` attribute contains the word `button`, but, naturally, clicking that directly won't trigger the change in radio button value we need.

I've spoken about this before [here](https://github.com/philc/vimium/issues/1554#issuecomment-91073708) (the issue is unrelated; I had misunderstood the title) and made a JSFiddle to test on [here](http://jsfiddle.net/mhwa9zep/1/). To cover all those cases properly will take a bit of work, but it should be doable.

I'll try to have a look at this when I get some time soon, unless anybody else would like to have a go at it.

**Comment by tayk045** [comment] 2015-07-31 03:22
Sorry I can't be of any help, I haven't got the slightest clue what you meant but it seem to me that the solution is on its way.

Thank you Matthew, please keep up the good work

**Comment by mrmr1993** [comment] 2015-10-23 18:48
I think this can be closed now #1822 has been merged.

**Closed** 2015-10-23 19:01 UTC

**Comment by rrsahutwo** [comment] 2015-11-13 10:38
We are movers and packers in Bangalore and many other big places in India. We are knowledgeable packers movers Bangalore to provide effective product packaging, moving, shifting, and moving and transportation solutions. We have a large system of packers & movers in Bangalore as well as across the nation. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:38
We become a aspect of the transportation industry in India to create it practical and safe for individuals. Care India Packers is quite well-known transportation organization for its high quality, quick solutions and economic moving features. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:38
Our qualified and knowledgeable group provides features like running, product packaging, unpacking, traveling, unloading, moving, vehicle-carrier and so on. We are best option what you can use to meet any of your domestic or official shifting needs. We create the perform of moving simple, simple, safe and smooth

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:38
You can know that shifting your house, workplace or company from one position to another is not simple for individuals. It is sometimes regarded to be a very stressful, stressful and traumatic job and probably it cannot be performed at only one hand. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
