### ISSUE TITLE
While Jumping across tabs : gets stuck with a tab cos' the page grabs focus on an element on the page like a textbox. 

### ISSUE THREAD

**Issue by squareofthehypotenuse** [philc/vimium#873] opened 2013-06-18 20:44 UTC
While Jumping across tabs, using K or J, gets stuck with a tab cos' the page grabs focus on an element on the page like a textbox. 

Is there a way to disable focus behavior on pages that has default focus to elements on page?

**Comment by smblott-github** [comment] 2016-03-06 13:45
I've wondered about doing this, but decided not to.  The problem is with inputs like the one I'm typing in here.  If I quickly change tabs (with `Ctrl-PageUp/Down`) to grab some info, I **do** want to be dropped back into insert mode when I return.  And this case is common and important, e.g. composing an email.

Unfortunately, we can't tell the difference between Chrome dropping us back into an input, and the page focusing the input.

Closing as v. old (and we don't have any good ideas).

**Closed by smblott-github** 2016-03-06 13:45 UTC
