### ISSUE TITLE
[Feature request] Map zoom in/out

### ISSUE THREAD

**Issue by alexcg1** [philc/vimium#4161] opened 2022-11-04 12:22 UTC
It would be great to have keys for zooming. I previously used [Vimvixen](https://github.com/ueokande/vim-vixen) where it's mapped to:

`zi` - zoom in
`zo` - zoom out
`zz` - zoom reset

**Comment by gdh1995** [comment] 2022-11-05 06:29
Duplicate of #1866 .

**Closed** 2023-12-09 00:08 UTC
