### ISSUE TITLE
increasing number of multiple Vimium instances in change context dropdown of chrome developer tools window

### ISSUE THREAD

**Issue by rockneverdies55** [philc/vimium#2073] opened 2016-03-28 17:25 UTC
in the screenshot below, only 3 instances shown but it gets worse and worse while working in the developers tools. I mean there becomes so many vimium options thus that I cannot even locate what I'm looking for in the context switch dropdown anymore after a while.

![image](https://cloud.githubusercontent.com/assets/4588562/14084329/3cdadbde-f4e8-11e5-98fa-bd0c342e9535.png)

I smell some kind of memory leak kind of issue...

**Comment by smblott-github** [comment] 2016-03-28 18:02
Thanks, @rockneverdies55.  I'll explain what's probably going on, then close this issue -- if you don't mind.

In your screenshot, the top Vimium is just Vimium, and the next two are Vimium's UI components.  They live in their own iframe.  In 1.54, you'll see Vimium and the HUD in every frame in the tab, and the vomnibar in the top frame only.  I guess that's the source of your issue.

In the next version (and due to #1838 and #2033), we will only be initialising UI components when Vimium isn't disabled (via exclusion rules).  If you disable Vimium on the sites you're working on, then Vimium shouldn't be polluting the dev console for you.

(There is a memory leak in newer Chrome versions, but that's due to a Chrome regression -- see #2055 and #2070.)

**Closed by smblott-github** 2016-03-28 18:02 UTC
