### ISSUE TITLE
Unable to copy to clipboard incognito mode

### ISSUE THREAD

**Issue by ssonal** [philc/vimium#2867] opened 2017-12-13 11:18 UTC
Both yanking text and copying current url to clipboard do not work while in incognito mode in Chrome. Is this a deliberate change?

Google Chrome | 63.0.3239.84 (Official Build) (64-bit)
OS | Mac OS X
Vimium version | 1.62

**Comment by smblott-github** [comment] 2017-12-13 11:25
Reproduced.  Probably a regression due to #2601.

**Comment by innaterebel** [comment] 2017-12-13 17:12
Working fine here on Windows 7 64-bit,
Chrome 64.0.3282.24 64-bit
Vimium 1.62

**Comment by smblott-github** [comment] 2017-12-14 11:27
Thanks, @innaterebel.  I went to look at this just now, and now cannot reproduce it.

**Comment by trou** [comment] 2017-12-14 22:36
I can reproduce on Debian Sid, Chrome Version 63.0.3239.108.

Normal mode works, Incognito mode does not.

**Comment by ym1234** [comment] 2017-12-20 20:36
Can reproduce on Arch linux 
Vimium 1.62.4
Chrome 63.0.3239.84

**Comment by arizzubair** [comment] 2017-12-20 21:23
Can reproduce on macos sierra 10.12.6
Vimium: 1.62.4
Chrome: Version 63.0.3239.84

**Comment by arizzubair** [comment] 2018-02-28 06:23
This issue seems to be fixed in vimium 1.63 version. 
Tested on vimium 1.63 on chrome 64 (mac os high sierra).

**Closed** 2018-02-28 06:25 UTC
