### ISSUE TITLE
Vimium blocks key in Unity Web game even after "Exclude on this page"

### ISSUE THREAD

**Issue by bayramkzk** [philc/vimium#4435] opened 2024-03-10 12:44 UTC
**Describe the bug**

I realized this issue while surfing on the web, at [this Unity web-build game](https://kubil6y.itch.io/topdown-shooter-demo).

**To Reproduce**

1. Go to URL https://kubil6y.itch.io/topdown-shooter-demo
2. Click "Exclude vim keys on this page" within Vimium
3. Press lowercase d while playing the game to move right

**Browser and Vimium version**

- Firefox 123.0.1
- Vimium 2.0.6
- Arch Linux, Plasma 6.0.1, Wayland Session

**Comment by philg-dev** [comment] 2024-03-28 03:40
I could reproduce the issue on my end.

I found out, that it doesn't matter if you exclude "All keys" on that page or just the `d` key - both still "eat" the key-event for some reason.

However a workaround that did solve the issue was to customize the Vimium key mappings.
I've added the following line to my "customize key mappings" settings to avoid the problem:

```
unmap d
```

There should probably be a way to change the way "excluded keys" on specific pages are handled, so that it behaves in the exact same way as if those keys were unmapped.

> (Disclaimer: I've noticed that the author of the add-on has a similar name as I do. I'm not the same person - I'm a very new user of Vimium and was just looking into things.)

**Comment by philc** [comment] 2024-03-28 04:03
I can't reproduce on master. I think this was fixed by #4402 in v2.1.0, which was submitted to the store earlier today. Can you try on master/v2.1.0 to see if it's still an issue?

**Comment by philg-dev** [comment] 2024-03-28 04:44
I've just started out with Vimium. I would love to confirm that it's fixed, however I'm on Windows 10 and I can't seem to get the `make.js` working in order to produce the proper Firefox `manifest.json` as mentioned in the `CONTRIBUTING.md`.

It just says to run this:
`./make.js write-firefox-manifest`

I've seen the `make.js` is supposed to run with "Deno"... I'm not familiar with that tool and I couldn't get it running immediately just now.

If you want me to confirm the fix on my end, I would appreciate some instructions on how to properly set up the project locally to test on Firefox.

**Comment by philg-dev** [comment] 2024-04-14 12:23
Since the new version is released in the meantime, I just tested it again.

The problem is fixed and simply adding "d" to the exclusions on the given site by  @bayramkzk properly allows for WASD movement in the game.

Tested on Firefox version 124.0.2 (64-bit) and Vimium version 2.1.2

I suggest this may be closed as fixed by #4402

**Closed** 2024-08-25 21:39 UTC
