### ISSUE TITLE
Add the ability to temporarily toggle vimium on/off for a page

### ISSUE THREAD

**Issue by jwmann** [philc/vimium#428] opened 2011-12-30 14:10 UTC
It would be nice if I could do a key combination that would disable vimium on the current page temporarily; furthermore it would be nice to have an editable list of domains in the settings that vimium would not run on.

**Comment by idf** [comment] 2015-04-28 02:58
@philc 
Same issue on google doc.

**Comment by tandroid1** [comment] 2015-06-08 17:11
It's certainly not just gmail. Any website has the ability to bind custom shortcuts. Additionally, other Chrome plugins have the ability to map any of these keys. For example, the [Vimsert](https://github.com/gabesullice/vimsert) plugin, allows you to open a vim editor within any text area. This does not work with Vimium because both bind to the same keys. I can't imagine a user disabling Vimium for each site that might have a form they could fill out, but I could see a user simply hitting shift + escape and disabling Vimium before using Vimsert. This might seem like an unlikely scenario, but in my opinion it seems likely that Vimium users might have other plugins that provide greater "vim-like" functionality and and would run into these types of conflicts. 

This is just one example, but I'm sure there are many others. The bottom line is that I don't think it makes sense to assume the user will have the foresight to know when Vimium will conflict with a site or plugin.

**Comment by smblott-github** [comment] 2015-06-08 17:13
@tandroid1.  Perhaps check [here](https://github.com/philc/vimium/wiki/Disabling-Vimium)?

**Comment by tandroid1** [comment] 2015-06-08 19:04
@smblott-github Yes, the escape key is one of the issues, but since it uses the ace vim editor, I would imagine most key bindings would conflict.

**Comment by mrmr1993** [comment] 2015-06-08 19:13
@tandroid1 the extension you linked looks like it uses a `<textarea>`, and so we automatically enter insert mode when it is focused. The only binding in insert more is `<esc>`/`<c-[>`, so this should be the only (but significant) clash.

**Comment by drwl** [comment] 2015-08-16 02:32
@philc @idf Even though google docs is an excluded page:
`https?://docs.google.com/*` with `*` keys excluded, escape still does not work as intended. This behavior resumes back to normal when vimium is disabled.

**Comment by smblott-github** [comment] 2015-08-16 05:59
@drwl.  To completely disable Vimium, you should leave the "Keys" empty.  Could that be your problem?  If not, perhaps open a new issue and explain what you expect to happen and what actually happens.

**Comment by drwl** [comment] 2015-08-16 06:31
@smblott-github It's interesting behavior to exclude * (all keys) versus leaving it blank that disables Vimium on a page. Nonetheless leaving it blank works!

**Comment by smblott-github** [comment] 2015-08-16 06:34
Great, @drwl.

We should probably close this issue.
It covers a variety of features and issues which have been implemented since the tread began.
If there are specific issues with specific features, open a new issue.

**Closed by smblott-github** 2015-08-16 06:34 UTC

**Comment by idf** [comment] 2015-08-16 12:50
Thanks @drwl @smblott-github  for the fix. 

When will there be a new vimium release for this fix?

**Comment by drwl** [comment] 2015-08-18 23:04
@idf If you want to turn off Vimium for Google docs, just leave the exclude keys field blank.

![Uploading Screen Shot 2015-08-18 at 4.04.00 PM.png…]()

Otherwise are you asking about something else?

**Comment by idf** [comment] 2015-08-20 04:22
@drwl is there a key combination to toggle vimium rather than disable it by URL entirely. I have tried ESC, it works in Google spreadsheet but not in google word.

**Comment by es6Test** [comment] 2016-03-02 07:09
Even if its disabled the css and js for vimium is spamming my network tab in dev tools.

**Comment by smblott-github** [comment] 2016-03-02 07:11
> Even if its disabled the css and js for vimium is spamming my network tab in dev tools.

@philc has raised this previously... #1838.

**Comment by es6Test** [comment] 2016-03-02 10:01
ah, ok thanks!

**Comment by masaeedu** [comment] 2017-10-21 16:57
@smblott-github As far as I can see the original feature requested is still not available. It isn't possible to enable vimium on a page where it is currently disabled without reloading the page. Being able to toggle it by clicking on the vimium extension icon would be useful.

**Comment by stevesan** [comment] 2019-04-21 16:03
Another +1 for this. I just uninstalled vimium again because of this issue... insert mode works ok, but it shows the "insert mode" toast. Also, very annoying when making my own webGL games. A simple global temporary-disable would make me happy (effectively a quicker uninstall/reinstall I guess, keeping settings)! I'm gonna try the exclude trick I guess..but it's pretty heavy-weight for a common use case.

**Comment by nicoandmee** [comment] 2023-05-19 15:03
+1 for this.
