### ISSUE TITLE
Firefox: Links inside forum posts (on some forums) do not work

### ISSUE THREAD

**Issue by VladimirMarkelov** [philc/vimium#2702] opened 2017-10-06 00:12 UTC
Besides incompatibility with TreeStyleTab(#2700) the current mechanism of opening links fails to open link in both current tab and new tab - it does nothing.

Example: open a forum thread http://forum.ru-board.com/topic.cgi?forum=81&active=11&topic=0902&start=960 - it is discussion about Mustek scanner. If you try to open any link above posts (e.g, any other page) - it works. If you try to open a link inside post (e.g, the link "Сайт" right under the Mustek logo) - it opens nothing: it shows a key combination hint, I press all required keys and then it just erases a hint for key combination as if it tries to open the link but fails.  So, I see the same page. Opening with mouse click works as expected: Mustek official site opens.

**Comment by mrmr1993** [comment] 2017-10-06 00:20
This is a duplicate of #2672, which is fixed in master by PR #2681. The fix will be included in the next release.

**Comment by VladimirMarkelov** [comment] 2017-10-06 00:22
I'm sorry. My bad - I overlooked existing issue when I searched for my troubles.

**Closed** 2017-10-06 05:43 UTC
