### ISSUE TITLE
Bookmarklet doesn't run when executed through vomnibar

### ISSUE THREAD

**Issue by marlun** [philc/vimium#1611] opened 2015-04-28 09:18 UTC
If I hit `b` and in the vomnibar try to run my "+ Pocket" bookmarklet (by hitting ENTER) nothing happends. If I click the bookmark manually in the bookmarks bar everything works fine. Worked fine a couple of days ago.

**Comment by smblott-github** [comment] 2015-04-28 09:27
That's odd.  The bookmarklet (installed from [here](https://getpocket.com/add/?ep=1)) is working for me...

**Comment by marlun** [comment] 2015-04-28 10:49
That's the one I've added too. I've tried in both Chrome stable and Carnary. I've got Vimium 1.5. Not sure how to debug it?

**Comment by smblott-github** [comment] 2015-04-28 10:51
Perhaps look for errors on the console (`Ctrl-Shift-I`)?

**Comment by marlun** [comment] 2015-04-28 10:56
Yes, I'm getting an error:

    Uncaught SyntaxError: Unexpected token %                VM160:1

**Comment by smblott-github** [comment] 2015-04-28 11:00
Hmm.  I just got a different error...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7368251/0d98042a-ed9e-11e4-9e44-d7a183aa1492.png)

**Comment by marlun** [comment] 2015-04-28 13:55
Not sure if I can do more to help?

**Comment by smblott-github** [comment] 2015-04-28 15:26
I'm not sure how to make progress either.  Using 1.50, the only fail case I've found is github (and only if you're logged in).  Everything else seems to work.

Let's pick a particular page.  Say [this one](http://www.bbc.com/news/business-32493745).  It saves to pocket just fine for me.  There are some errors on the console:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7373248/2de6ef0a-edc3-11e4-8048-ac56c1c22fdd.png)

But these are coming from the web page itself.

Ideas:
- Try the page linked above, and report back any errors.
- Create a clean Chrome profile, and see if you still get the same problem.

**Comment by marlun** [comment] 2015-04-28 17:42
I'm always getting the same error:

    Uncaught SyntaxError: Unexpected token %                VM160:1

What's the recommended way of creating a clean chrome profile?

**Comment by mrmr1993** [comment] 2015-04-28 17:50
Easiest way is to reate an empty directory, then use it as your profile by following the instructions under "Running from a custom location" [here](https://www.chromium.org/user-experience/user-data-directory).

**Comment by rmetzler** [comment] 2015-04-28 21:01
I also get the same error. I think it broke with the last Vimium update. I use Chrome on OSX if this is relevant.

```
Uncaught SyntaxError: Unexpected token %                 VM121:1
```

The `VMxxx:1` seems to be site-specific.

**Comment by mrmr1993** [comment] 2015-04-28 23:49
> The VMxxx:1 seems to be site-specific.

The virtual machine (VM) code gives information about which javascript context the error has come from. Unfortunately in this case, it's not very helpful to us.

A couple of things you could do to help us debug:
* copy the bookmarklet from your bookmarks and paste it here, so we can make sure we're looking at the same version
* try to run the bookmark directly from the background page by
  - opening the background page's console (instructions in the bullet points of [this comment](https://github.com/philc/vimium/issues/1296#issuecomment-66560887))
  - running the code below (replacing `BOOKMARK_TEXT` with the url you've copied from your bookmark)
  - switching to a tab within 5 seconds, when the bookmark should try to run
  - checking whether there were any errors or if it worked.

Code for background page:
```js
setTimeout(function(){chrome.tabs.update({"url": " BOOKMARK_TEXT"});}, 5000);
```

**Comment by smblott-github** [comment] 2015-04-29 04:47
Here's the complete background-page command for pocket (for me):

    setTimeout(function(){chrome.tabs.update({"url": " javascript:(function(){var e=function(t,n,r,i,s){var o=[1681363,3799528,2161300,2540919,5264808,2108548,4688354,3792361,2314604,5325129];var i=i||0,u=0,n=n||[],r=r||0,s=s||0;var a={'a':97,'b':98,'c':99,'d':100,'e':101,'f':102,'g':103,'h':104,'i':105,'j':106,'k':107,'l':108,'m':109,'n':110,'o':111,'p':112,'q':113,'r':114,'s':115,'t':116,'u':117,'v':118,'w':119,'x':120,'y':121,'z':122,'A':65,'B':66,'C':67,'D':68,'E':69,'F':70,'G':71,'H':72,'I':73,'J':74,'K':75,'L':76,'M':77,'N':78,'O':79,'P':80,'Q':81,'R':82,'S':83,'T':84,'U':85,'V':86,'W':87,'X':88,'Y':89,'Z':90,'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,'\/':47,':':58,'?':63,'=':61,'-':45,'_':95,'&':38,'$':36,'!':33,'.':46};if(!s||s==0){t=o[0]+t}for(var f=0;f<t.length;f++){var l=function(e,t){return a[e[t]]?a[e[t]]:e.charCodeAt(t)}(t,f);if(!l*1)l=3;var c=l*(o[i]+l*o[u%o.length]);n[r]=(n[r]?n[r]+c:c)+s+u;var p=c%(50*1);if(n[p]){var d=n[r];n[r]=n[p];n[p]=d}u+=c;r=r==50?0:r+1;i=i==o.length-1?0:i+1}if(s==269){var v='';for(var f=0;f<n.length;f++){v+=String.fromCharCode(n[f]%(25*1)+97)}o=function(){};return v+'e0a93c0ccb'}else{return e(u+'',n,r,i,s+1)}};var t=document,n=t.location.href,r=t.title;var i=e(n);var s=t.createElement('script');s.type='text/javascript';s.src='https://getpocket.com/b/r4.js?h='+i+'&u='+encodeURIComponent(n)+'&t='+encodeURIComponent(r);e=i=function(){};var o=t.getElementsByTagName('head')[0]||t.documentElement;o.appendChild(s)})()"});}, 5000);

(This works for me, just like clicking on the link, or selecting the link from the Vomnibar.)

**Comment by vincentbernat** [comment] 2015-04-29 06:12
I am also running into the same problem with the Twitter bookmarklet. For some reason, it is stored with URL escapes, unlike other bookmarklets.

```
javascript:%28function%28%29%7Bwindow.twttr%3Dwindow.twttr%7C%7C%7B%7D%3Bvar%20D%3D550%2CA%3D450%2CC%3Dscreen.height%2CB%3Dscreen.width%2CH%3DMath.round%28%28B%2F2%29-%28D%2F2%29%29%2CG%3D0%2CF%3Ddocument%2CE%3Bif%28C%3EA%29%7BG%3DMath.round%28%28C%2F2%29-%28A%2F2%29%29%7Dwindow.twttr.shareWin%3Dwindow.open%28%27https%3A%2F%2Ftwitter.com%2Fshare%27%2C%27%27%2C%27left%3D%27%2BH%2B%27%2Ctop%3D%27%2BG%2B%27%2Cwidth%3D%27%2BD%2B%27%2Cheight%3D%27%2BA%2B%27%2Cpersonalbar%3D0%2Ctoolbar%3D0%2Cscrollbars%3D1%2Cresizable%3D1%27%29%3BE%3DF.createElement%28%27script%27%29%3BE.src%3D%27https%3A%2F%2Fplatform.twitter.com%2Fbookmarklets%2Fshare.js%3Fv%3D1%27%3BF.getElementsByTagName%28%27head%27%29%5B0%5D.appendChild%28E%29%7D%28%29%29%3B
```

**Comment by smblott-github** [comment] 2015-04-29 10:16
Perhaps one of you could try the following:
- Go to the bookmark manager and create a new bookmark.
- Give it a name, and this as its target:

    javascript:(function(){var t=document,n=t.location.href,r=t.title; console.log(n,r);})()

- Try it out.  It should output the URL and title of the current tab on the console.  It's a fragment of the Pocket bookmarklet.
- Report back...

**Comment by marlun** [comment] 2015-04-29 10:40
I tried it on http://www.meetup.com/Vim-London/events/221570539/ and got

    http://www.meetup.com/Vim-London/events/221570539/ April Meetup - Vim London (London, England) - Meetup

**Comment by smblott-github** [comment] 2015-04-29 10:56
OK.  Thanks @marlun.  So the bookmarklet is running, and appears to be running in the correct context.  Which is a good start.

Here are three versions of the Pocket bookmarklet:

```
javascript:(function(){var e=function(t,n,r,i,s){var o=[1681363,3799528,2161300,2540919,5264808,2108548,4688354,3792361,2314604,5325129];var i=i||0,u=0,n=n||[],r=r||0,s=s||0;var a={'a':97,'b':98,'c':99,'d':100,'e':101,'f':102,'g':103,'h':104,'i':105,'j':106,'k':107,'l':108,'m':109,'n':110,'o':111,'p':112,'q':113,'r':114,'s':115,'t':116,'u':117,'v':118,'w':119,'x':120,'y':121,'z':122,'A':65,'B':66,'C':67,'D':68,'E':69,'F':70,'G':71,'H':72,'I':73,'J':74,'K':75,'L':76,'M':77,'N':78,'O':79,'P':80,'Q':81,'R':82,'S':83,'T':84,'U':85,'V':86,'W':87,'X':88,'Y':89,'Z':90,'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,'\/':47,':':58,'?':63,'=':61,'-':45,'_':95,'&':38,'$':36,'!':33,'.':46};if(!s||s==0){t=o[0]+t}for(var f=0;f<t.length;f++){var l=function(e,t){return a[e[t]]?a[e[t]]:e.charCodeAt(t)}(t,f);if(!l*1)l=3;var c=l*(o[i]+l*o[u%o.length]);n[r]=(n[r]?n[r]+c:c)+s+u;var p=c%(50*1);if(n[p]){var d=n[r];n[r]=n[p];n[p]=d}u+=c;r=r==50?0:r+1;i=i==o.length-1?0:i+1}if(s==269){var v='';for(var f=0;f<n.length;f++){v+=String.fromCharCode(n[f]%(25*1)+97)}o=function(){};return v+'e0a93c0ccb'}else{return e(u+'',n,r,i,s+1)}};var t=document,n=t.location.href,r=t.title;var i=e(n);var s=t.createElement('script');})()
javascript:(function(){var e=function(t,n,r,i,s){var o=[1681363,3799528,2161300,2540919,5264808,2108548,4688354,3792361,2314604,5325129];var i=i||0,u=0,n=n||[],r=r||0,s=s||0;var a={'a':97,'b':98,'c':99,'d':100,'e':101,'f':102,'g':103,'h':104,'i':105,'j':106,'k':107,'l':108,'m':109,'n':110,'o':111,'p':112,'q':113,'r':114,'s':115,'t':116,'u':117,'v':118,'w':119,'x':120,'y':121,'z':122,'A':65,'B':66,'C':67,'D':68,'E':69,'F':70,'G':71,'H':72,'I':73,'J':74,'K':75,'L':76,'M':77,'N':78,'O':79,'P':80,'Q':81,'R':82,'S':83,'T':84,'U':85,'V':86,'W':87,'X':88,'Y':89,'Z':90,'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,'\/':47,':':58,'?':63,'=':61,'-':45,'_':95,'&':38,'$':36,'!':33,'.':46};if(!s||s==0){t=o[0]+t}for(var f=0;f<t.length;f++){var l=function(e,t){return a[e[t]]?a[e[t]]:e.charCodeAt(t)}(t,f);if(!l*1)l=3;var c=l*(o[i]+l*o[u%o.length]);n[r]=(n[r]?n[r]+c:c)+s+u;var p=c%(50*1);if(n[p]){var d=n[r];n[r]=n[p];n[p]=d}u+=c;r=r==50?0:r+1;i=i==o.length-1?0:i+1}if(s==269){var v='';for(var f=0;f<n.length;f++){v+=String.fromCharCode(n[f]%(25*1)+97)}o=function(){};return v+'e0a93c0ccb'}else{return e(u+'',n,r,i,s+1)}};var t=document,n=t.location.href,r=t.title;var i=e(n);var s=t.createElement('script');s.type='text/javascript';s.src='https://getpocket.com/b/r4.js?h='+i+'&u='+encodeURIComponent(n)+'&t='+encodeURIComponent(r);e=i=function(){};})()
javascript:(function(){var e=function(t,n,r,i,s){var o=[1681363,3799528,2161300,2540919,5264808,2108548,4688354,3792361,2314604,5325129];var i=i||0,u=0,n=n||[],r=r||0,s=s||0;var a={'a':97,'b':98,'c':99,'d':100,'e':101,'f':102,'g':103,'h':104,'i':105,'j':106,'k':107,'l':108,'m':109,'n':110,'o':111,'p':112,'q':113,'r':114,'s':115,'t':116,'u':117,'v':118,'w':119,'x':120,'y':121,'z':122,'A':65,'B':66,'C':67,'D':68,'E':69,'F':70,'G':71,'H':72,'I':73,'J':74,'K':75,'L':76,'M':77,'N':78,'O':79,'P':80,'Q':81,'R':82,'S':83,'T':84,'U':85,'V':86,'W':87,'X':88,'Y':89,'Z':90,'0':48,'1':49,'2':50,'3':51,'4':52,'5':53,'6':54,'7':55,'8':56,'9':57,'\/':47,':':58,'?':63,'=':61,'-':45,'_':95,'&':38,'$':36,'!':33,'.':46};if(!s||s==0){t=o[0]+t}for(var f=0;f<t.length;f++){var l=function(e,t){return a[e[t]]?a[e[t]]:e.charCodeAt(t)}(t,f);if(!l*1)l=3;var c=l*(o[i]+l*o[u%o.length]);n[r]=(n[r]?n[r]+c:c)+s+u;var p=c%(50*1);if(n[p]){var d=n[r];n[r]=n[p];n[p]=d}u+=c;r=r==50?0:r+1;i=i==o.length-1?0:i+1}if(s==269){var v='';for(var f=0;f<n.length;f++){v+=String.fromCharCode(n[f]%(25*1)+97)}o=function(){};return v+'e0a93c0ccb'}else{return e(u+'',n,r,i,s+1)}};var t=document,n=t.location.href,r=t.title;var i=e(n);var s=t.createElement('script');s.type='text/javascript';s.src='https://getpocket.com/b/r4.js?h='+i+'&u='+encodeURIComponent(n)+'&t='+encodeURIComponent(r);e=i=function(){};var o=t.getElementsByTagName('head')[0]||t.documentElement;o.appendChild(s)})()
```

The first two are abbreviated, the third is the full thing.  The first two don't do anything, but they shouldn't produce any error messages on the console.  Would you be able to check which is the first one to produce and error message?

Another thing to try is simply taking the full text of the Pocket bookmarklet (the third line above) and running it in the console (`Ctrl`-`Shift`-`I`).

**Comment by marlun** [comment] 2015-04-29 11:40
I tried them all, 1-2 gave no error message in the console and nothing else happaned.

The third one gave no error message but the Pocket "dropdown" which usually says "Page saved" or something like that showed but it said "Error saving".

The same thing happends if I run the third on in the console.

**Comment by smblott-github** [comment] 2015-04-29 12:37
I'm at a loss, for now.  Any ideas, @mrmr1993?

**Comment by felixfoertsch** [comment] 2015-04-29 13:24
Same error for my Pinboard bookmarklets.
Chrome Version 42.0.2311.135 (64-bit)
Mac OS X Yosemite 10.10.3 (14D136)

**Comment by marlun** [comment] 2015-04-29 13:35
When running the commands I can see the request in the network tab.

1. The request URL looks like getpocket.com/b/r4.js?h=XXX. The XXX differs between if I run your third line in the console and if I run the bookmarklet through the bookmaks bar.
2. If I view the response of both requests they differ in two different places:
    * The variable PKT_STATUS is "1" on the successful and "3" on the unsuccessful
    * If I change all ; in the response to a newline at the end of the response there's a diff in the `e.th='XXX'` part where the successful request has what looks like a hash and the other has an empty string.

```javascript
setTimeout(function(){var e=new PKT_BM
e.th="XXX"
e.init()
e.save()},1)
```

Not sure if this says anything useful. Any other part of the request I should check for differences?

**Comment by rmetzler** [comment] 2015-04-29 20:24
My bookmarklets I had problems with (Delicious and Instapaper)  were both URLencoded. Not sure why. I urldecoded them (somehow the instapaper bookmarklet missed `+` signs after that), fixed the problems and it works now. I also ran into Google showing me this bookmark site for the first time, so maybe Google changed something in the background.

**Comment by marlun** [comment] 2015-04-29 20:27
Not sure why I didn't try that but that did solve it for me (sorry). Never had to do it before though. Did vimium do this for you before and changed it recently?

**Comment by felixfoertsch** [comment] 2015-04-29 20:34
Ha, I just opened my Bookmark Manager. It is a completely new interface (chrome://bookmarks/). Perhaps they changed something during the transition period?

My bookmarklets seem to work again; however now the popup for my pinboard is associated with the webpage I open the bookmarklet on... so it blocks it on every unknown page.

**Comment by mrmr1993** [comment] 2015-04-29 21:04
@rmetzler's comment above agrees with what I'd been suspecting all along; the `chrome.tabs.update` function isn't treating encoded `javascript:` URLs properly.

Can everyone check whether decoded versions of bookmarklets work correctly?

**Comment by rmetzler** [comment] 2015-04-30 00:00
When I drag a bookmarklet into my favourites it is saved URLencoded. Clicking it works fine, but it Vimium will throw this parsing error.

I tested this with the [PrintWhatYouLike bookmarklet](http://www.printwhatyoulike.com/bookmarklet). (highly recommended). Decoding is problematic, because `+` in URLs is another way to encode a space. So this should be tested if you want to fix this in Vimium.

**Comment by smblott-github** [comment] 2015-04-30 06:23
> When I drag a bookmarklet into my favourites it is saved URLencoded.

And when *I* do that, it is not URLencoded.  So that's problematic, to start with.

It looks like non-URLencoded `javascript:` URLs are working in 1.50, but URLencoded URLs are not. They're generating a Javascript VM error message.  Is that right?

1.50 appears to be handling `javascript:` URLs differently from 1.49 ([here](https://github.com/philc/vimium/pull/1139/files#diff-9d24083a8251f08044c0aa4871e4574cL28)).  However, reviewing the 1.49 behaviour, I can't figure out how `javascript:` URLs ever worked ([here](https://github.com/philc/vimium/blob/1.49/lib/utils.coffee#L99)). The `hasChromePrefix` test is `false`.  Thereafter, both remaining branches seem to produce nonsense URLs.

(In a URLencoded `javascript:` URL, can the prefix be anything other than `javascript:%`?  That is, the next character has to be a non-URL character, which is encoded.  Is that right?)

**Comment by rmetzler** [comment] 2015-04-30 07:20
>> When I drag a bookmarklet into my favourites it is saved URLencoded.
> And when I do that, it is not URLencoded. So that's problematic, to start with.

Chromium 41 on Ubuntu doesn't do this neither. Chrome 42 on OS X did this yesterday for me. I run Vimium 1.50 on both.

> In any non-trivial URLencoded javascript: URL, can the prefix be anything other than javascript:%?

Yes, e.g. there might be a `(` as the next character which is [allowed unencoded in URLs](http://stackoverflow.com/a/1856809).  Usually curly brackets are the first character which becomes encoded and breaks the parser (at least that's what I think I've seen).
```
javascript:(function(){alert(1);})();
```

**Comment by smblott-github** [comment] 2015-04-30 07:59
Is the following proposition true?

Adding

```Coffeescript
if isJavascriptUrl query
  if isUrlEncoded query
    decodeURIComponent query
  else
    query
```

would fix this issue.

(Or are there issues related to Chrome versions in the mix too?)

**Comment by mrmr1993** [comment] 2015-04-30 16:05
I've opened [Chromium issue 483000](https://code.google.com/p/chromium/issues/detail?id=483000) for the underlying Chrome issue. Since the omnibox and bookmarks decode all javascript URLs, the right thing to do is always decode them before we pass them to `chrome.tabs.update` too, at least until the Chrome team fix the issue.

**Comment by philc** [comment] 2015-05-01 06:24
Great investigative work.

**Comment by rmetzler** [comment] 2015-05-03 19:42
I'm under the impression PR #1621 didn't really fixed the bookmarklet issue. Can someone verify?

**Comment by mrmr1993** [comment] 2015-05-03 19:53
@rmetzler can you give an example of a bookmark that doesn't work with 1.51?

**Comment by longouyang** [comment] 2015-05-03 22:07
@mrmr1993 Here's one that doesn't work for me:

Encoded:

~~~~
javascript:(function()%7Bfunction callback()%7B(function(%24)%7Bvar jQuery%3D%24%3B%24("header%2C .header%2C %23header%2C .sidebar%2C %23sidebar%2C .social%2C %23social").remove()%3B%24('*').filter(function()%7B return this.style %26%26 this.style.position %3D%3D 'fixed' %7D).remove()%7D)(jQuery.noConflict(true))%7Dvar s%3Ddocument.createElement("script")%3Bs.src%3D"https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js"%3Bif(s.addEventListener)%7Bs.addEventListener("load"%2Ccallback%2Cfalse)%7Delse if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()
~~~~

Decoded version:

~~~~{js}
(function(){
  function callback(){
    (function($){
      var jQuery=$;$("header, .header, #header, .sidebar, #sidebar, .social, #social").remove();
      $("*").filter(function(){ return this.style && this.style.position == "fixed" }).remove()})(jQuery.noConflict(true))
  }

  var s=document.createElement("script");
  s.src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js";
  if (s.addEventListener){
    s.addEventListener("load",callback,false)
  } else if(s.readyState){
    s.onreadystatechange=callback
  }
  document.body.appendChild(s);
})()
~~~~

**Comment by marlun** [comment] 2015-05-04 09:05
Pocket stopped working for me again after 1.5.1 now it doesn't even work if I decode the string which I get from https://getpocket.com/add/?ep=1

**Comment by smblott-github** [comment] 2015-05-04 14:24
@marlun.  Confirmed.  I'm seeing the same.  That's weird.  I thought we had this fixed.  For sure it was working on my other machine.

@mrmr1993.  It works with 9f2c0ac1cf97635d4dd5f33b114aed092a3e1f6e.  Do you think we should go back to that?  Although there's an element of Heisenbug about this one.  We could end up thrashing.

**Comment by smblott-github** [comment] 2015-05-04 14:49
More info... The problem seems to be that `decodeURI` is failing with the message `URI malformed`.

Perhaps we should just `try`/`catch`?  Certainly that will work for this example.

(The message is on the console of the background page.)

**Comment by mrmr1993** [comment] 2015-05-04 15:59
@smblott-github see my comment in #1636. We may have to decode them manually to make

```js
javascript:alert(25 % 20);alert(25%20);
```
and similar work correctly.

**Comment by rmetzler** [comment] 2015-05-04 22:20
I recognized there are two different functions: `decodeURI` and `decodeURIComponent`.

I used @longouyang's bookmarklet, turned it into a JavaScript String and ran both functions:

```js
eval(decodeURI('javascript:(function()%7Bfunction callback()%7B(function(%24)%7Bvar jQuery%3D%24%3B%24("header%2C .header%2C %23header%2C .sidebar%2C %23sidebar%2C .social%2C %23social").remove()%3B%24(\'*\').filter(function()%7B return this.style %26%26 this.style.position %3D%3D \'fixed\' %7D).remove()%7D)(jQuery.noConflict(true))%7Dvar s%3Ddocument.createElement("script")%3Bs.src%3D"https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js"%3Bif(s.addEventListener)%7Bs.addEventListener("load"%2Ccallback%2Cfalse)%7Delse if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()'))
```
=>
```
VM414:1 Uncaught SyntaxError: Unexpected token %(anonymous function) @ VM413:2InjectedScript._evaluateOn @ VM309:883InjectedScript._evaluateAndWrap @ VM309:816InjectedScript.evaluate @ VM309:682
```

```js
eval(decodeURIComponent('javascript:(function()%7Bfunction callback()%7B(function(%24)%7Bvar jQuery%3D%24%3B%24("header%2C .header%2C %23header%2C .sidebar%2C %23sidebar%2C .social%2C %23social").remove()%3B%24(\'*\').filter(function()%7B return this.style %26%26 this.style.position %3D%3D \'fixed\' %7D).remove()%7D)(jQuery.noConflict(true))%7Dvar s%3Ddocument.createElement("script")%3Bs.src%3D"https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.7.1%2Fjquery.min.js"%3Bif(s.addEventListener)%7Bs.addEventListener("load"%2Ccallback%2Cfalse)%7Delse if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)()'))
```
=>
```
VM392:1 Refused to load the script 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js' because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com collector-cdn.github.com".
(anonymous function) @ VM392:1(anonymous function) @ VM392:1(anonymous function) @ VM391:2InjectedScript._evaluateOn @ VM309:883InjectedScript._evaluateAndWrap @ VM309:816InjectedScript.evaluate @ VM309:682
```

So it looks for me that `decodeURIComponent` should actually work fine. If somebody could link a good how-to on how to set up a Google Chrome plugin dev environment, I would've tried the actual code change.

**Comment by mrmr1993** [comment] 2015-05-04 23:28
@rmetzler both functions still throw an error for my example above

```
javascript:alert(25 % 20);alert(25%20);
```

but that example runs when manually entered to bookmarks/the omnibox. See [my comment](https://github.com/philc/vimium/pull/1636#issuecomment-98809384) on #1636 for an alternative that should match the native behaviour.

> Google Chrome plugin dev environment

I use Chrome (obviously), Vim, [vim-coffee-script](https://github.com/kchmck/vim-coffee-script) and [Coffeetags](https://github.com/lukaszkorecki/CoffeeTags) when I'm working on Vimium. Any other editor/IDE with equivalent tools should work too.

**Comment by smblott-github** [comment] 2015-05-05 08:20
Folks... We merged 96af254973cc15714894c822a2c8a4a66a34fbef, which should fix this issue in the next release.  Special thanks to @mrmr1993.

**Closed** 2015-05-05 08:19 UTC

**Comment by felixfoertsch** [comment] 2015-05-27 22:13
Hey guys, when will the next release be? This feature is like my most used of them all. I'd love it to be fixed.

**Comment by smblott-github** [comment] 2015-05-28 04:38
Not sure, I'm afraid, @felixfoertsch.

**Comment by rmetzler** [comment] 2015-06-02 08:32
Could you maybe just create a bugfix release?

**Comment by mrmr1993** [comment] 2015-07-20 18:06
A fix for the Chromium issue [has landed](https://code.google.com/p/chromium/issues/detail?id=483000#c6), it should be available in the Chrome version-after-next. This being the case, we'll need to ensure the fix we added is only applied to the relevant versions once it's made it into the Chrome Dev channel.

**Comment by mrmr1993** [comment] 2015-08-03 02:31
> A fix for the Chromium issue [has landed](https://code.google.com/p/chromium/issues/detail?id=483000#c6), it should be available in the Chrome version-after-next.

Update: the fix has landed in dev at Chrome version 46.0.2467.2, so the fix should only be applied to versions before that.

**Comment by felixfoertsch** [comment] 2015-09-26 15:04
Hey guys, this still doesn't work for me.

**Comment by mrmr1993** [comment] 2015-09-26 15:07
@felixfoertsch which Chrome version are you running?

**Comment by felixfoertsch** [comment] 2015-09-26 15:09
Mac OS X El Capitan 10.11 Beta (15A278b), Chrome Version 45.0.2454.101 (64-bit)

**Comment by mrmr1993** [comment] 2015-09-26 15:30
I can't seem to repro on Ubuntu 15.04, Chrome Version 45.0.2454.101. Can you give an example of a bookmarklet that isn't working?

**Comment by felixfoertsch** [comment] 2015-09-26 15:32
I used to use this one for bookmarking before the change.

```
javascript:q=location.href;if(document.getSelection){d=document.getSelection();}else{d='';};p=document.title;void(open('https://pinboard.in/add?showtags=yes&url='+encodeURIComponent(q)+'&description='+encodeURIComponent(d)+'&title='+encodeURIComponent(p),'Pinboard','toolbar=no,scrollbars=yes,width=750,height=700'));
```

**Comment by rajeevksahu** [comment] 2015-11-13 11:24
People in Bangalore are so active that they do not have additional here we are at moving and moving. Packing all the items is really a tough job. While packaging, there is excellent probability of breaking of expensive items. Specialist creates you to perform well without any damage.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment] 2015-11-13 11:24
Professional movers have excellent abilities, thus they do not damage your fill by their actions. Proper pure cotton, curtains and containers are used to package items. When we fill and get rid of items by own, then are chances to damage us too. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment] 2015-11-13 11:24
Dealing up with loads is a tiring job. Lots of effort is demanded running and unloading process. If you did this job by own, then tiredness did not release you so quickly. Movers packers Bangalore reduce your perform and provides Hassel 100 % free moving.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment] 2015-11-13 11:24
In Indian, this is a trend to contact for visitors whenever you are going for moving and moving to other position. But if we think once, did they really like it when you contact and disturb them. As we are active in our lifestyle, they are too. But experts have reduced this disturbance to a large degree. Packing moving Bangalore becomes very simple because of our expert and experienced packers and movers.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by melkster** [comment] 2022-04-05 08:20
Hello! I still get the error message `Uncaught SyntaxError: Unexpected token %` when I try to run bookmarklets from the vomnibar. Clicking on the bookmark works. I've tried both in Google Chrome and in Brave. Here's script that I'm trying to run:

```javascript
javascript: (async () => {
  var accessToken = JSON.parse(Object.values(window.localStorage).find(ls => {
    try {
      return ls.includes("AccessToken");
    } catch {}
  }))?.secret;
  try {
    await navigator.clipboard.writeText(accessToken);
    alert("Copied AccessToken to clipboard.");
  } catch(error) {
    alert("Failed to copy AccessToken:" + error);
  }
})();
```
