### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by AndyKriger** [philc/vimium#892] opened 2013-08-01 13:48 UTC
Chrome version: 29.0.1547.22 beta
Vimium version: 1.43
OS version: Ubuntu Linux

After running Chrome for a while, Vimium will be taking up nearly 2G of private memory according to the Task Manager. This brings Chrome to a crawl. Seen this a few times in the past few days. Not even using vimium at all during that time but the extension is active. Looks like some kind of memory leak during general background operations.

**Comment by bvdeenen** [comment] 2015-04-02 07:06
My linux system running chromium browser has been running for 4 days, and vimium is using 1.2 GB.
I have two windows open, and one of the windows is running a js application that continually switches the content.
In the 'stats for nerds' I see that vimium has 1.2 GB private memory, and 20M memory 'proportional' whatever that is.
The memory usage doesn't seem to be increasing with the activity of my javascript application, but just by opening and closing a few windows, 1 see 1MB increases, that don't get released.
Is there anything I can do to help find this leak?
![image](https://cloud.githubusercontent.com/assets/47788/6959294/7aa4abfe-d917-11e4-8a86-8d998905a60c.png)

**Comment by smblott-github** [comment] 2015-04-02 10:55
Wow. 1.2GB is a lot of memory.  For me memory is sitting between 45 and 55 MB (and chrome has been running and heavily used for six days).  Might there be a platform or chrome-release factor at play?

(For comparison, Adblock Plus is using 80MB, and the Hangouts extension 130MB.)

Let's reopen this, and see if we get any more reports.

**Comment by bvdeenen** [comment] 2015-04-02 12:45
I've stopped and restarted vimium this morning, and it's now 81MB. Without me doing anything, it suddenly jumped 300kB up in the task manager.
My platform is kubuntu:

$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l
                                                                                                                                                                                                         
 $  uname -a                                                                                                                                       
Linux iln-dt-bart 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux                 

$ chromium-browser --version
Chromium 37.0.2062.120 Ubuntu 14.04

**Comment by smblott-github** [comment] 2015-04-02 12:50
@bvdeenen...  It might be worth upgrading chromium. 37 is pretty old.

**Comment by bvdeenen** [comment] 2015-04-02 13:03
Ok I've narrowed it down a bit. It has to do with opening (or probably closing) pages.
In my case, I was running an application that switched pages (from javascript) every few seconds via `window.open(url, '_self')`
Starting this page fresh, allowed me to see a leak of a few 100 kB every page switch in Vimium. But this adds up!
You'll hit a GB leak in a few days.
Funny enough, my own browser application doesn't seem to be leaking memory, but it seems to be triggering something in vimium.

Anyway, I think you have a reproducible issue; just create two html pages with a window.setTimeout and a window.open to the other one.

**Comment by bvdeenen** [comment] 2015-04-02 13:05
Ok I'll upgrade chromium, and will let you know if the issue continues

**Comment by bvdeenen** [comment] 2015-04-02 13:15
ok I've upgraded chromium-browser
$ chromium-browser --version
Chromium 41.0.2272.76 Ubuntu 14.04

But the leak pattern still occurs the same when my javascript page-switching application is running. You lose a few 100 k every few page switches. I started at around 25MB, and it's now 26.4 MB.

**Comment by smblott-github** [comment] 2015-04-04 08:18
Losing 100kb is not such a big deal.  Chromium is caching various stuff.  The real problem is whether Chromium ever gives the memory back.  I too see jumps in memory (up to 10MB after creating a few tabs), but Chrome gives it back (asynchronously).

**Comment by AdrianoFerrari** [comment] 2015-11-05 10:59
I've been trying to trace a memory leak in my own app, but in running outside of Incognito I seem to have found one in Vimium. Did the 3 snapshot technique, and found MessagePort is being held by vimium (Retained size: .
![screenshot - 15-11-05 - 05 47 57 am](https://cloud.githubusercontent.com/assets/323678/10966335/ef9d59ce-8380-11e5-9d78-604fe23f4894.png)

I can send you the heap snapshots if that would help.
I left both Vimium and my app (https://gingkoapp.com) running overnight between snapshots 1 & 2.

**Comment by ahxxm** [comment] 2016-03-30 02:54
![image](https://cloud.githubusercontent.com/assets/1286225/14130431/748b9eb4-f665-11e5-9f35-1dcc5ed28515.png)
Seems so.
My environment: OS X 10.11.4, chrome version: Version 49.0.2623.110 (64-bit)
I've 8 tabs open, in which 3 are pinned. Close and reopen an unpinned github issue page, memory usage increase by 2Mib ...

**Comment by ahxxm** [comment] 2016-03-30 03:06
tried latest master `a332f0cc7139c9185fcea3e82c800915712b5491`, memory consumption keeps at about 66MB.

**Comment by smblott-github** [comment] 2016-03-30 04:42
Closing.
@ahxxm... See #2055.  Short version, there seems to be a memory leak due to a regressing in Chrome.

**Closed by smblott-github** 2016-03-30 04:42 UTC
