### ISSUE TITLE
Vomnibar not working on Firefox 56, use LocationBar instead?

### ISSUE THREAD

**Issue by fkjogu** [philc/vimium#2707] opened 2017-10-07 08:26 UTC
When typing `o` to go to a new URL the vomnibar pops up with a blinking cursor, but it is not possible to type. The keystrokes are just ignored. Can somebody reproduce?

Would it be possible to just focus the LocationBar of Firefox (like when pressing `ctrl``l`)? This would have the advantage of all the features provided by Firefox itself, missing in this extension.

**Comment by PhilippWendler** [comment] 2017-10-14 09:58
Do you have NoScript installed? I stumbled across this as well, and the workaround from #2608 seems to fix it for now, so this could be a duplicate.

**Comment by jeaye** [comment] 2017-11-30 00:25
I've confirmed this is a dupe of #2608 and I think it should be closed. Thanks, @PhilippWendler.

**Closed** 2017-11-30 07:17 UTC
