### ISSUE TITLE
Console error message be clear by vimium.

### ISSUE THREAD

**Issue by bestvow** [philc/vimium#2947] opened 2018-02-07 07:22 UTC
Keep Console open , then refresh page , the Console output message auto hide due to vimium.
![1234](https://user-images.githubusercontent.com/24888709/35903508-79779eba-0c1a-11e8-9b2e-d5eecae0b53e.gif)

This error from Chrome v64

**Comment by smblott-github** [comment] 2018-02-07 07:45
This is fixed in `master`.  The issue is that Chrome is clearing the console when the Vomnibar iframe is loaded.  In `master`, that now only happens on demand (when it is needed).

Closing for now.  Should be fixed in anything at or after 1.62.10.

**Closed by smblott-github** 2018-02-07 07:45 UTC
