### ISSUE TITLE
Travis builds are failing...

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#2273] opened 2016-09-25 11:35 UTC
E.g., see [here](https://travis-ci.org/philc/vimium/builds/162399331).

That's a rebuild of a build that previously succeeded, so it looks like a Travis issue, or perhaps our Travis config file.

The tests for #2272 pass locally for me, but fail on Travis.

It looks like that big regexp in visual mode ([here](https://github.com/philc/vimium/blob/master/content_scripts/mode_visual.coffee#L32)) is causing the problem.

**Comment by yandavid** [comment] 2016-09-27 06:34
Hi,

My latest PR (https://github.com/philc/vimium/pull/2276) contains a fix for this issue (among other things).

It looks like the latest version of coffeescript (`1.10.0 -> 1.11.0`) does not like that long regex. I know next to nothing about coffeescript, and even less about its internals, but it looks like the problem is somewhere in these changesets: https://github.com/jashkenas/coffeescript/compare/1.11.0...master.

**Closed** 2016-09-27 11:07 UTC
