### ISSUE TITLE
J and K do not work well together with Panorama Tab Groups extension (hidden tabs)

### ISSUE THREAD

**Issue by silviubogan** [philc/vimium#3593] opened 2020-06-08 08:50 UTC
**Describe the bug**
J and K do not work well together with [this extension](https://github.com/projectdelphai/panorama-tab-groups).

Taken from the description of Vimium:
```
J, gT go one tab left
K, gt go one tab right
```

**To Reproduce**
1. Install the [Panorama Tab Groups](https://github.com/projectdelphai/panorama-tab-groups) extension.
2. Make 2 tab groups with new tabs created one after another in random groups.
3. Switch to a group.
4. Try to use J and K keys to go through the list of tabs.
5. It goes through the hidden tabs ignoring the separation between tab groups.

**Browser and Vimium version**
Firefox: 77.0.1
SO: Linux 5.4.0-33-generic (Ubuntu 20.04)
Vimium: 1.66

Thank you.

**Comment by gdh1995** [comment] 2020-06-08 09:09
Confirmed. This is because in Firefox [a tab has a `hidden` status](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab), which doesn't exist on Chrome, and Vimium haven't support it.

**Comment by gkaklas** [comment] 2020-07-11 12:20
I believe this is a duplicate of #2998 :thinking:

**Comment by 010penetrator** [comment] 2022-03-30 17:03
I have the same problem. Have to revert to hitting <C-Tab> and <C-S-Tab>

**Comment by philc** [comment] 2024-05-30 04:39
Closing as a duplicate of #2998.

**Closed by philc** 2024-05-30 04:39 UTC
