### ISSUE TITLE
Once Vomnibar loses focus, Vimium practically stops working -- is this deliberate or a bug?

### ISSUE THREAD

**Issue by saheel1115** [philc/vimium#1506] opened 2015-02-24 20:37 UTC
I am currently using the `b49d1bf` version of `master`.

Step 1: Vomnibar.activate (or Vomnibar.activateInNewTab)
Step 2: Click anywhere on the page which takes focus away from Vomnibar

*After this, all Vimium keybindings stop working.*

To make Vimium start functioning again, I have to either:
1. Click on the Vomnibar using a mouse to give back the focus to it, or
2. Switch to some other tab or other application window, and then come back to this tab. This also gives back the focus to Vomnibar and everything resumes working (for the time being anyway).

I feel the expected behavior after Step 2 above should be that the Vomnibar disappears completely. If not that, at least Vimium should not stop working (!) in which case I could do Vomnibar.activate again and get the Vomnibar to work again.

**Comment by mrmr1993** [comment] 2015-02-24 20:41
This is partially fixed in the `master` branch here; Vimium remains functional after blurring the Vomnibar. It seems like hiding and disabling the Vomnibar when it's blurred is the logical thing to do, and an easy change.

(@smblott-github, this sounds like an easy fix for a part of the problem we discussed over email, too.)

**Comment by mrmr1993** [comment] 2015-02-24 21:01
Had another look, it's because the Vomnibar is blurred but its `iframe` is still focused.

Adding the following to `VomnibarUI::initDom` (in `pages/vomnibar.coffee`) should do the trick:

```coffee
@input.addEventListener "blur", => @input.focus()
```

**Comment by saheel1115** [comment] 2015-02-24 21:28
It works, great! Basically, now, even on clicking elsewhere the Vomnibar doesn't lose focus (gets 'blurred'). If there's a better patch in the future, and if you happen to remember this issue, can you please add a comment here?

**Comment by saheel1115** [comment] 2015-02-24 21:32
I am closing this issue for now.

**Comment by mrmr1993** [comment] 2015-02-24 21:36
@saheel1115 Can you re-open this? I'll throw together a proper fix when I get home from the pub/tomorrow, and I'd like to be able to associate it with this issue. This is related to something Steve and I were discussing anyway, so I don't think there should be any trouble in getting the fix in the codebase.

**Comment by smblott-github** [comment] 2015-03-05 08:39
#1511 was intended to fix this.  It hides the vomnibar on blur.  It looks like this approach isn't going anywhere, because we get blur events when we change tab.  We need another approach... (?).

**Comment by smblott-github** [comment] 2015-03-05 15:48
> If there's a better patch in the future, and if you happen to remember this issue, can you please add a comment here?

@saheel1115.  Any chance you could try #1517 (which seems to be a better fix - hopefully)?

**Comment by saheel1115** [comment] 2015-03-05 16:03
Okay, I'll do that (in a day or two) and report back.

**Closed** 2015-03-06 11:51 UTC
Labels: release-blocker, smb-watching

**Comment by rrsahutwo** [comment] 2015-11-13 10:39
You can search us on internet or you can also ask about us from your family associates, friends and others. Our prior pleased customers and customers can tell you about us and our effective solutions. Our customers are not only facilitated with the effective features, but also are benefited with the cheap costs.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:40
We are knowledgeable enough to comprehend about the fitness of the automobiles to take you to remote destinations that is why we are always careful to manage all the automobiles for their finish fitness. Our expert mechanics take a look minutely to create sure the ability and capacity of automobile to run on the long routs. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:40
A daily observation of the automobiles let us know about what is thing that needs to be mended and changed with the new ones. No matter whether your location is near or long far from the previous position, our automobiles and other features of Packing Moving Bangalore take you and your luggage to the new location with protection. Customer protection is the thing of the first priority for us.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:40
Trained and knowledgeable motorists at Care India Packers create our Packers and Movers Services in Bangalore more effective and safer. We take it into the consideration that a automobiles and motorists to carry them should be fit so that the journey can be more comfortable.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
