### ISSUE TITLE
I can not input anything in find mode "/". It only works when open the help "?"

### ISSUE THREAD

**Issue by fuatto** [philc/vimium#3313] opened 2019-05-05 18:55 UTC
- Chrome version:  74.0.3729.131
- OS version: macOS Mojave 10.14.4
- Vimium version: 1.64.5

**Comment by gdh1995** [comment] 2019-05-06 01:52
Caused by some inner changes of Chrome 74, and will be fixed by #3277 .

**Comment by fuatto** [comment] 2019-05-06 18:29
@gdh1995 Great work man an thanks for the info!

**Closed** 2019-05-12 07:01 UTC
