### ISSUE TITLE
Automatically scrolls back to previous photo in Facebook timeline

### ISSUE THREAD

**Issue by jayadeepk** [philc/vimium#1164] opened 2014-09-23 08:40 UTC
Steps to reproduce:
* Open a photo in facebook timeline by either with keyboard or mouse.
* Close the photo with either keyboard or mouse.
* Now scroll down using 'd' or 'j' using keyboard.
* After 1 to 2 seconds it scrolls back to that photo.
This happens every time and stops only after scrolling once with mouse or touchpad.

I use version Vimium 1.45 downloaded from google chrome webstore.

**Comment by konovalov-** [comment] 2015-12-14 17:51
It's not a Fb bug. Same things happens even if you scroll vk.com feed. It's really annoying - 	
periodically I have to "remember" current scroll position by pressing 'arrow down' or 'page down' keys. Version 1.53

**Comment by smblott-github** [comment] 2015-12-14 18:01
The same thing happens if you **disable** `j`/`k` scrolling on FB and use the native bindings instead.

I think it's a FB bug.

**Comment by mrmr1993** [comment] 2015-12-14 19:18
I think it's related to [this Chromium issue](https://code.google.com/p/chromium/issues/detail?id=342307), and caused by a workaround for an incorrect implementation of `scrollTop` in WebKit(/Blink).

**Comment by smblott-github** [comment] 2016-01-30 12:51
Closing.
Suspected to be a Chromium issue, not a Vimium issue.

**Closed by smblott-github** 2016-01-30 12:51 UTC
