### ISSUE TITLE
[FF] Open new tab after last tab

### ISSUE THREAD

**Issue by wladmis** [philc/vimium#2893] opened 2017-12-28 15:00 UTC
Current behavior is: when `t' key is pressed, Firefox opens new tab after current tab. I found it less convenient than if new tab was opened after last tab in the tab list.

Please, change the behavior to open new tab after the last tab if you find it reasonable, or make some way to able to change it by user preferences.

**Comment by drwilly** [comment] 2017-12-30 15:18
Firefox controls this via `browser.tabs.insertRelatedAfterCurrent`.
However opening a new tab through Vimium seems to ignore this setting.

**Comment by reinerh** [comment] 2018-01-02 15:25
Duplicate of #2670.

**Comment by wladmis** [comment] 2018-01-02 15:55
> Firefox controls this via browser.tabs.insertRelatedAfterCurrent

No, it's not what I want. I want that Firefox opens related tab after current tab but a new tab after last tab.

It's no duplicate of #2670.

**Comment by philc** [comment] 2020-01-10 05:53
An option for this was implemented in #2895 and will go out with the next Vimium release in late Jan. Thanks for the request @wladmis.

**Closed by philc** 2020-01-10 05:53 UTC

**Comment by gdh1995** [comment] 2020-01-10 06:11
@philc Sorry for my mistake but now I find the `position=end` may not work on Firefox: if `chrome.tabs.create {position: null}`, Firefox will open a tab next to a current tab...

Maybe I just tested the PR on Chrome. I'll put a new PR to fix it. Sorry again.

**Comment by philc** [comment] 2020-01-10 07:55
position:null opens a new tab after the current tab on Chrome also; it's not Firefox specific. That's how it's always been. Note that when I press cmd+T in Chrome, the new tab is inserted at the end. I'm not sure why Vimium's T and Chrome's Cmd+T behave differently. Maybe historical legacy?

The code in master preserves the current tab behavior for both Firefox and Chrome, and just adds some new options without changing the default behavior. I'm not sure we should change the default behavior at this point to reconcile Vimium to Chrome and Firefox's defaults. I prefer "new tab after existing tab" and have gotten used to it; if we change it now, many users will notice and ask about it.

**Comment by gdh1995** [comment] 2020-01-10 07:57
Oh you're right, then I'll split `position=end` and `position=undefined`.

**Comment by gdh1995** [comment] 2020-01-10 08:35
Oh, I find the root cause which failed my tests:
on Firefox, `chrome.tabs.create({url:'http://localhost/', index: null, openerTabId: 3})` will create a tab just next to the tab of `id=3`. And if no `openerTabId`, its default action is to open a tab at the end. So I think the new PR is still useful since `tabIndex=9999` is enough.

**Comment by m6z** [comment] 2021-01-22 14:59
Hello,
This works well in Firefox: `map t createTab position=end`
But something like this does not seem to be implemented:
`map F LinkHints.activateModeToOpenInNewTab position=end`
Or is it supported in some way?
Thanks!

**Comment by gdh1995** [comment] 2021-01-26 13:21
No, no such option in `LinkHints`. Because `LinkHints` just simulate mouse actions, and it's your browser which decides whether and where to open a new tab.

**Comment by wenfangdu** [comment] 2023-03-01 13:26
@gdh1995 Hello, is `position=end/start...` documented anywhere? I only found this option in this [commit](https://github.com/philc/vimium/commit/2acf8dd51d6c3378e994bcbc34e21f6f15ee55f2).

**Comment by gdh1995** [comment] 2023-03-12 14:49
Um no, it's somehow new and then not added into document.
