### ISSUE TITLE
vimium not working for pdf files

### ISSUE THREAD

**Issue by vmrekhate** [philc/vimium#1243] opened 2014-11-15 12:07 UTC
I cannot use j/k bindings for scrolling through pdfs, when open by the native pdf reader in chrome on ubuntu. The vimium icon shows blue (loaded).
Please help.
Vimium version : 1.45
Chrome Version : 37.0.2062.94

**Comment by alcoheca** [comment] 2015-09-22 23:20
Viumium 1.5.2 and Chrome 44.0.2403.155 (64-bit) also have this problem. Viumium doesn't play with the internal PDF viewer and tab navigation is rendered useless.

Is there a version permutation known working for PDF tabs? I open a lot of PDFs in chrome.

I've followed the path of all the related PRs and it looked like this should be fixed inside the beta/testing options page.. Is that true?

**Comment by rrsahutwo** [comment] 2015-11-13 10:48
Actually it doesn't matter much for us that what type of moving our clients have to execute or perform. We have sufficient moving features and qualified employees to create all types of moving effective with protection benefits. Our relocations features will ultimately result in a relaxed day for each and every client who comes to us. 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers Hyderabad">Movers and Packers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers Bangalore">Movers and Packers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers Mumbai">Movers and Packers Mumbai</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:48
On the contrary if you seek the services of any irresponsible transportation company, you may even get into a big issues wondering about what to do and how to do in that situation. But you will be pleased to know that with the help of our movers packers Bangalore , you can execute all these jobs without any pressure and within little time. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers Gurgaon">Movers and Packers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers Delhi">Movers and Packers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers Pune">Movers and Packers Pune</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:48
So if you are seeking the help of expert experts, our qualified packers, employees, drivers and other employees will be the best choice for meeting your needs.
When you have a variety of the baggage and you have to travel a lengthy trip for moving, it is natural to encounter pressure for the protection of the items. That is why you will like to have the strategy service for your items. We take excellent appropriate want to create acquire all the features such as the strategy. 

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers Chennai">Movers and Packers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers Noida">Movers and Packers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers Navi Mumbai">Movers and Packers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers Thane">Movers and Packers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers Ghaziabad">Movers and Packers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers Faridabad">Movers and Packers Faridabad</a>

**Comment by rrsahutwo** [comment] 2015-11-13 10:48
You need not to search for other experts anywhere else. The service of the strategy creates you totally exempt from the mess of your useful factors on the way. The ultimate Bangalore of the Packers and Movers Services in Bangalore at #Expert5th is to provide one stop remedy of moving. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by dragonxlwang** [comment] 2016-02-18 20:05
I am also having this problem but my expectation of vimium can be much easier satisfied --- I just want to be able to navigate across the PDF tabs --- now, when navigating using H/L to left and right tabs and if the current tab is a PDF tab, then it traps there ---- one can only use mouse or chrome default navigation key to move around.

**Comment by mrmr1993** [comment] 2016-02-18 23:38
I believe (unless Chrome's PDF handling has changed) that you can press `<esc>` to defocus the pdf, anf then Vimium works correctly

**Comment by dagerikhl** [comment] 2016-11-08 08:22
I am having this exact issue. I see it's referenced here, #1014, too.
This is annoying behaviour, especially if I use `J` and `K` to navigate through my many open tabs, but  have 1 pdf-tab open. I then have to switch to `CTRL+TAB`/`CTRL+SHIFT+TAB` to navigate to the next/previous tab.

### Expected behaviour
Any tab with an open pdf-file should act as any other tab in Chrome, with all shortcuts (especially `J` and `K`) enabled.

### Current behaviour
All Vimium shortcuts stops working when navigating to a tab with an open pdf file, eg. `file:///C:/Users/user/Downloads/pdf.pdf` or [http://www.pdf995.com/samples/pdf.pdf](http://www.pdf995.com/samples/pdf.pdf).
Vimium is loaded (blue extension icon).
Vimium, curiously enough, seems to work *while* the pdf is loading.
Pressing `ESC` does *not* unfocus the pdf and allow Vimium shortcuts to work.

### Steps to reproduce
Open any pdf in a new tab in Chrome.

### Info
**Platform:** Windows 10 (experience on Windows 7 as well).
**Browser:** Google Chrome 54.0.2840.71 m.
**Vimium options:** Allowed in inkognito: yes, Allow access to file urls: yes.

**Comment by smblott-github** [comment] 2016-11-08 10:18
Interesting.  Vimium *is* running on that page you link to, @dagerikhl.  And we're seeing the `keydown` events, but **not** the `keypress` events which we use to trigger most commands.

This works: 

    map <c-e> Vomnibar.activate

(We handle control keys on `keydown`.)

If we moved *all* key handling to `keydown`, then this issue might be fixed.  And that might be possible now (or soon), because Chrome Stable now has `event.key`.

**Comment by dagerikhl** [comment] 2016-11-08 18:23
Thank you for the reply.
That's quite enlightening! And I now understand why it isn't working although it's loaded.

I tested with your suggested mapping, and I can confirm that it works as expected on my system as well.

Is this a fix that can be expected in the near future? Would be really great if the `keydown` event could be used, as it seems to fix the issue perfectly.

**Comment by KVohra95** [comment] 2017-02-12 22:04
@dagerikhl how did you get this working with the mapping? I added that line to my vimium custom key mappings but vimium doesnt work in the native chrome pdf viewer nor does it work in pdf.js, this is something that I would really like to see fixed because if vimium doesnt work in all tabs then I may go back to standard chrome keyboard shortcuts even though I would really like to use vimium. Thanks

**Comment by dagerikhl** [comment] 2017-02-12 22:57
@KVohra95 I am afraid I have not been able to fix the issue. Vimium still doesn't work for any pdf file open. The "solution" discussed above referred to the fact that shortcuts which included the CTRL-key worked, like the `<c-e> Open URL, bookmark or history entry` shortcut. No other shortcuts worked.

Now, however, it seems that not even CTRL-activated shortcuts works, at least not on my system.

Would really like to see a fix for this soon, as it's quite a hindrance when maneuvring through a lot of tabs, where one or more is a pdf.

**Comment by KVohra95** [comment] 2017-02-13 14:00
I see, yes it is really a hindrance for me too, I know that chrome extensions can communicate so I was wondering if the vimium dev could collab with the pdf.js dev to get this to work it would be great.

**Comment by KVohra95** [comment] 2017-03-01 00:06
@smblott-github is there any way of moving to the keydown binding or for us to define this fix ourselves in the settings of vimium? This would be a great help

**Comment by smblott-github** [comment] 2017-03-01 07:09
@KVohra95 There's no existing setting, but it's a change (moving all key processing to `keydown`, that is) that we should be considering anyway.

**Comment by KVohra95** [comment] 2017-03-01 09:54
oh ok cool, I was just wondering whether we could map the keybinding with the custom key mappings

**Comment by KVohra95** [comment] 2017-03-16 11:42
I have found a solution, you have to use vimium++ which is a fork of vimium and use my fork of pdf.js chrome extension as shown here: https://chrome.google.com/webstore/detail/pdf-viewer/lcopgfbpbmionefhhgbamgmejggljpbb. I have also added a few vimium related keybindings such as h and l to go forward back a page and / for searching within the document

**Comment by DiogoFerrari** [comment] 2017-03-21 16:06
In the lack of a better solution for now, I did this dirt workaround [here](https://github.com/DiogoFerrari/vi-keybinding).

**Closed** 2017-03-24 07:01 UTC

**Comment by jrnkng** [comment] 2022-07-27 14:08
Still happening for me? Anyone got a solution?

**Comment by csumpasd** [comment] 2022-09-07 10:48
happening for me too, not sure if a chromium update changed the pdf viewer since then

**Comment by InsigMath** [comment] 2022-10-22 22:47
Using vimium and pdf tabs still dont work. I can use the arrow keys to move up and down the document but cannot use typical vimium navigation keys or the x key unfortunately.

**Comment by zzeitt** [comment] 2022-10-27 03:50
This extension ([PDF Viewer for Vimium C](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj/)) works well for me.

**Comment by iamashwin99** [comment] 2023-12-12 23:57
Any native solutions for this yet?

**Comment by au-summer** [comment] 2025-01-08 21:49
> This extension ([PDF Viewer for Vimium C](https://chrome.google.com/webstore/detail/pdf-viewer-for-vimium-c/nacjakoppgmdcpemlfnfegmlhipddanj/)) works well for me.

this only supports j and k for scrolling, sadly
