### ISSUE TITLE
1.62.4 is clearing the console for no reason

### ISSUE THREAD

**Issue by niksosf** [philc/vimium#2907] opened 2018-01-08 11:54 UTC
Hi there, 

Does it also happen to anyone that console gets cleared almost immediately after loading? 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/79443/34669654-fcbc673e-f472-11e7-80ac-2ee9a072a3f8.gif)

**Comment by Cyperwu** [comment] 2018-01-09 01:45
Same issue here

**Comment by TimvdLippe** [comment] 2018-01-27 18:33
This started appearing after upgrading to Chrome 64, while this was working just fine in Chrome 63. Closing and opening the devtools shows all console messages again.

**Comment by JackieLin** [comment] 2018-01-30 15:03
My chrome version is 64.0.3282.119, and I have the same problem.

**Comment by smblott-github** [comment] 2018-01-30 15:10
Cannot reproduce here (Chrome 63 an 64).

(It's not at all obvious how Vimium *could* clear the console.  Anybody?)

**Comment by innaterebel** [comment] 2018-01-30 18:22
Well, Chrome 65 and can reproduce.
The actual steps are: on any web page have DevTools console opened then hit F5 to reload.

Could it be the vomnibar.html like in some other issues? The console is cleared when loading completes.
(I am not presuming it IS Vimium that clears the console, but some DevTools changes in Chrome 64 now let the likes of vomnibar.html to confuse it?)

**Comment by AndrewSouthpaw** [comment] 2018-02-02 01:04
It looks like vimium is causing a redirect after page load, and so the console clears.

![bug](https://user-images.githubusercontent.com/5187404/35711479-efb9ee32-0771-11e8-9919-713ebfff9ee9.gif)

**Comment by smblott-github** [comment] 2018-02-02 07:22
OK.  So that's the Vomnibar pre-loading in it's iframe.  It's been preloaded like that for years, so this is a change in behaviour from Chrome.

The Vomnibar is preloaded for performance reasons.  The interface is sluggish if we load the Vomnibar on demand.  I'll look at that decision again.

**Comment by TimvdLippe** [comment] 2018-02-02 11:59
I have opened an upstream issue for Chromium and they are actively investigating: https://bugs.chromium.org/p/chromium/issues/detail?id=806527

**Comment by ohjames** [comment] 2018-02-11 17:04
Same issue is affecting cvim.

**Comment by richardrobinsonx** [comment] 2018-02-16 00:09
Workaround: 

1. Open Console
2. Navigate to settings (gear icon on top right)
3. Select "Preserve log"

It's obviously not a fix, but allows me to debug with Vimium enabled

**Comment by smblott-github** [comment] 2018-02-16 11:00
I'm hoping that this will be fixed in v1.63, which is in the Chrome Store Now.

**Comment by TimvdLippe** [comment] 2018-02-16 13:39
I can confirm that v1.63 is working properly with devtools now :tada: @smblott-github much appreciated to fix this issue!

**Closed** 2018-02-16 13:40 UTC

**Comment by AndrewSouthpaw** [comment] 2018-02-16 17:02
You're fantastic, thanks so much @smblott-github!
