### ISSUE TITLE
Firefox 59: default keybindings (like `Ctrl+Shift+T` or `Ctrl+D`) stopped to work

### ISSUE THREAD

**Issue by actionless** [philc/vimium#2925] opened 2018-01-24 15:54 UTC
even adding the following to custom key mappings does not helps:
```viml
unmap <c-T>
map <c-T> restoreTab
```

`unmap <c-d>` which is suggested in readme also have no affect

UPD:
In Firefox 58 it works.
Also in Firefox 59 the following hotkeys are working fine when vimium is disabled.

**Comment by NPN** [comment] 2018-01-25 07:49
This also includes the following keybindings (and there may be more): `Ctrl+L`, `Ctrl+K`, and `Ctrl+F`.

**Comment by wavexx** [comment] 2018-02-04 23:28
It seems that any key which is bound by vimium (such as "L") acts this way.
If you "unmap l", for example, "Ctrl+L" will correctly select the location bar.

Maybe the extension now has to forward/bubble up the event if it isn't interested?

**Comment by smblott-github** [comment] 2018-02-05 06:29
> Maybe the extension now has to forward/bubble up the event if it isn't interested?

It already does.  (In principle, at least.)

**Comment by smblott-github** [comment] 2018-02-05 06:39
Could somebody experiencing this issue:

- leave `l` mapped within Vimium,
- go [here](https://f.smblott.org/keyboard),
- hit `Control-l`, and
- post the result back here.

That page just shows some properties of the keyboard events.

**Comment by NPN** [comment] 2018-02-05 07:10
Okay, this is weird. If I press `d`, `f`, `j`, `k`, or `l` (again, this may not be every broken key), no events are triggered. The corresponding browser shortcuts for these keys are broken.

This doesn't happen for every Vimium mapping, though. For example, `t` and `n` trigger no events, but `Ctrl-T` and `Ctrl-N` work fine.

What's even stranger is that if I quickly alternate between any two of the broken keys, such as `j` and `k`, I can get `keyup` events to fire—but only `keyup` events.

This might be related to a larger issue with keybindings in Firefox 59. For example, I've noticed that in Gmail, trying to copy text with `Ctrl-C` opens up the Compose window instead. And, in Google Docs, trying to paste via `Ctrl-V` types a `v` instead.

**Comment by wavexx** [comment] 2018-02-05 08:47
On Mon, Feb 05 2018, Ryan Huang wrote:
> This might be related to a larger issue with keybindings in Firefox
> 59. For example, I've noticed that in Gmail, trying to copy text with
> `Ctrl-C` opens up the Compose window instead. And, in Google Docs,
> trying to paste via `Ctrl-V` types a `v` instead.

Which platform are you on?

On linux and with GTK, firefox 57+ has become increasingly worse in
terms of keybindings. FF does not override shortcuts for the GTK
keyboard mode, which means that when "emacs style" editing is set,
almost no FF keybinding work because most are swallowed by the input
field itself. And it has been marked as a WONTFIX.

FF 57+ has been a trainwreck in terms of usability for me.

**Comment by NPN** [comment] 2018-02-05 09:23
I'm on Arch Linux/i3, and using the [`firefox-beta-bin`](https://aur.archlinux.org/packages/firefox-beta-bin/) package (version 59.0b6-1 at time of writing).

**Comment by actionless** [comment] 2018-02-05 12:15
@wavexx for me it's fine on 58 (compiled with GTK+3), but not on 59

**Comment by wavexx** [comment] 2018-02-05 16:35
On Mon, Feb 05 2018, Yauhen Kirylau wrote:
> @wavexx for me it's fine on 58 (compiled with GTK+3), but not on 59

Same here. Issue started with FF 59b4 (gtk3 on debian experimental).

**Comment by hackel** [comment] 2018-03-05 17:57
So is the consensus that this is a Firefox bug, with no way to work around it?  It also prevents me from opening menus.  E.g. <a-f> triggers LinkHints.activateMode as if alt wasn't pressed at all.  I _can_ use <a-e> to bring up the edit menu, and the arrow keys to get where I want to go.  The biggest impact on my workflow is definitely missing <c-l> top activate the location bar.  I'm working on training myself to use the vomnibar instead, but that darn muscle-memory is hard to break!

**Comment by NPN** [comment] 2018-03-05 20:43
After searching more carefully through Bugzilla, it appears to be this bug: [Browser keyboard shortcuts (eg copy Ctrl+C) don't work on sites that use those keys with resistFingerprinting enabled](https://bugzilla.mozilla.org/show_bug.cgi?id=1433592). Disabling `privacy.resistFingerprinting` does the trick for me: `Ctrl-C` works correctly in Gmail, and shortcuts such as `Ctrl+L` and `Ctrl+F` work properly when Vimium is enabled.

**Comment by Thorin-Oakenpants** [comment] 2018-03-27 23:58
^^ landed in FF59.0.2

**Closed** 2018-03-28 05:42 UTC

**Comment by hackel** [comment] 2018-08-29 23:10
Confirmed that disabling resistFingerprinting allows e.g. Alt-F to work to bring up the file menu, but this isn't a solution, merely a workaround.
