### ISSUE TITLE
Find in page with regular expressions doesn't work in Chrome on MacOS

### ISSUE THREAD

**Issue by andrea-berling** [philc/vimium#4261] opened 2023-06-08 12:51 UTC
**Describe the bug**
Find in page using  regular expressions doesn't work in Chrome on MacOS, neither when using \r at the end of the search query, nor by enabling "Treat find queries as JavaScript regular expressions". The count of matches seems to be correct, but when using n to navigate to the next match, it goes to the next "regular" match, instead of the next regex match. See "To Reproduce" for an example

**To Reproduce**
1. Go to URL [https://cloud.google.com/monitoring/mql/reference](https://cloud.google.com/monitoring/mql/reference)
2. Click `/` to start a search
3. Write `val` in the search query. You should get something similar to this: ![image](https://github.com/philc/vimium/assets/25068541/37451fb9-7ce3-4667-aeb8-16a85cd217c7)
4. Now write `\b` after `val` to match the string `val` followed by a blank character. You should get something similar to this (note that the number of matches decreases, but the highlighted match is still for just `val`): ![image](https://github.com/philc/vimium/assets/25068541/aa4579f5-11f0-4a0c-83a4-b80871045631)
5. Click `Enter` and `n`, you should get something like this (note that the next highlighted match is still just for `val`): ![image](https://github.com/philc/vimium/assets/25068541/0930e066-2391-4eed-a336-99501c040005)

**Browser and Vimium version**

Chrome version: `114.0.5735.90 (Official Build) (arm64)`
OS Version: `macOS Version 13.4 (Build 22F66)`
Vimum version: `1.67.4`

**Comment by wjianbo** [comment] 2023-08-24 23:25
I reproduced the behavior in Chrome on MacOS.
Additionally, I found the metacharacters `^` and `$` are not working either.
I tried to improve it by myself for a couple of days, And I want to create a pull request later.

**Comment by andrea-berling** [comment] 2023-08-27 10:24
@wjianbo that is great to hear, looking forward to see the PR

**Comment by wjianbo** [comment] 2023-09-04 01:04
@andrea-berling I've made the PR but I am not sure whether it would be merged.
Maybe you can try out yourself if you really need this feature.

**Comment by andrea-berling** [comment] 2023-09-04 12:05
@wjianbo Nice job mate, it works but I have the following feedback:
- It doesn't really work out-of-the-box: to make it work I needed to take your change (commit `02921a790eb31b2804792331e8ae9b7bca96476f`) and cherry-pick it on top of tag `1.67.1` (commit `4ed2ca96de09f9fa74202a7984677662e4b214b1`). Without doing this, I run into the following errors upon clicking Enter after entering my search query and using `n` to go to the next match respectively:
![image](https://github.com/philc/vimium/assets/25068541/301533ac-d7d3-43ae-9915-9d4f00fd434a)
- The match count is correct, but the first match is wrong. Not to worry though, as soon as I start navigating matches with `n` and `N` only correct matches are navigated to:
![image](https://github.com/philc/vimium/assets/25068541/3a6b14df-9ba1-46c9-8aab-45630e5b08af)
![image](https://github.com/philc/vimium/assets/25068541/096458a8-ac43-44c6-9bf0-9cfcfb8dad4e)
![image](https://github.com/philc/vimium/assets/25068541/9a5d110a-529d-4160-ad2d-c32d4e83b55c)
- For the rest, it works exactly as I wanted 🙂 I hope it gets merged soon, hopefully as part of a minor release before 2.0, so it becomes available quicker

**Comment by wjianbo** [comment] 2023-09-04 12:23
@andrea-berling Thank you for the feedback.

Yes, I encountered the same error with the original source code. I created separate PRs because they address different issues. This is my first time trying to contribute to a project, so I'm not sure if this is correct.

I hope it gets merged too. @philc Would you please review my PRs?

**Comment by wjianbo** [comment] 2023-09-06 02:27
@andrea-berling Hi~
I tried to reproduce the problem mentioned in your feedback but failed. The first match is correct on my PC. (using the same page you provide.) Strange thing.

Btw, I am using [my forked version](https://github.com/wjianbo/vimium), with the 2 PRs and the latest updates merged.

**Comment by wjianbo** [comment] 2023-09-06 04:19
@andrea-berling 
Accidentally deleted my former replay. 
I've looked into the problem (the first match is wrong) mentioned in your feedback and I think I've fixed it!
The fix has been committed to the same branch.
You can try [my forked version](https://github.com/wjianbo/vimium) with the 2 PRs and latest updates merged.

@philc 
Would you please review my PRs?
- #4298
- #4299 
Thank you for your great work!

**Closed** 2023-09-22 05:45 UTC
