### ISSUE TITLE
gi - not focusing the cursor to the end of the text already present in the first input on the page

### ISSUE THREAD

**Issue by chintan357** [philc/vimium#4275] opened 2023-07-09 07:20 UTC
So this is something I would like to see as  a feature in upcoming updates.

At present case if I search `vimium` on google, it will gonna show the search result page for the query `vimium`. Now I need to search for `vimium github` because the search results were not specific to what I was looking for. Pressing 'gi' takes me to the first input but the **cursor stays at the beginning** of the `vimium` inside the input box.

What I really wish is to have a feature that will **put the cursor to the end of the text** if present inside the input box.

Thank you everyone for this awesome extension 💖

**Comment by atlasshruggedbyaynrand** [comment] 2023-07-10 00:18
This seems to be specific to google.com and I'd consider it a pretty big problem since a lot of people still use Google Search.

It's not specific to 'gi'. Focusing it with 'f' also focuses the textbox at the start.

This does not happen with other sites (e.g. YouTube, Bing, Brave, DuckDuckGo).

Is there any way to add a "force focus text box at end" command or option?

**Comment by philc** [comment] 2023-07-10 07:02
Thanks for reporting. This is a duplicate of #4274. It's been fixed in master, but is not yet released to the store.

**Closed by philc** 2023-07-10 07:02 UTC
