### ISSUE TITLE
Find mode is not focused by default

### ISSUE THREAD

**Issue by diegovincent** [philc/vimium#3311] opened 2019-05-03 18:10 UTC
When I press `/` to enable find mode, the `/` feedback is displayed on the bottom of the page, however if I press any other key, nothing happens. However, if I first enter `yy` and then type `/`, the find text field is focused and then everything works as expected. I can also click on the find field, but we are using vimium because we do not want to touch the mouse after all.

I am using version 1.64.5 on Chrome 74 in Ubuntu 18.04.2 LTS. Any ideas how to fix this?

**Comment by shosti** [comment] 2019-05-03 20:07
Also noticing this issue since a recent update, using chromium 74.0.3729.108 on Linux.

**Comment by ytang17** [comment] 2019-05-03 20:48
Same issue, using Chrom Version 74.0.3729.131 (Official Build) (64-bit) on macOS Mojave 10.14.3

**Comment by ngoonee** [comment] 2019-05-03 23:46
Duplicate of https://github.com/philc/vimium/issues/3298

**Comment by krzkrzkrz** [comment] 2019-05-04 05:05
Happening here too OSX Mojave, Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Closed** 2019-05-12 07:01 UTC
