### ISSUE TITLE
Escape key caught by Vimium

### ISSUE THREAD

**Issue by ripdajacker** [philc/vimium#499] opened 2012-03-06 09:30 UTC
Vimium catches the keystroke for escape, even when out of input mode. The easiest way to show this is on Facebook chat, where you in the old version could press escape twice and close the chat.

**Comment by yoshuawuyts** [comment] 2015-01-06 14:09
God this is annoying, have run into it multiple times now. Would be cool if it could be fixed, without http://stackoverflow.com/questions/12927752/keydown-keyup-events-not-detecting-the-escape-key-being-pressed-on-input-text-fi I would've been lost.

**Comment by smblott-github** [comment] 2015-01-06 14:18
What behaviour would you like to see from `Esc`?

**Comment by ZombieHippie** [comment] 2015-01-06 14:21
Vimium does not allow propagation of any webpage's Escape keyup bound
events. If you are not engaged in a Vimium activity(like `f` for find link)
then there it only seems to inhibit the abilities of the user.

**Comment by smblott-github** [comment] 2015-01-06 14:44
> Vimium does not allow propagation of any webpage's Escape keyup bound
events

Really?

Test:
```coffeescript

watch = (type) ->
  document.addEventListener type, (event) ->
    para = document.createElement "p"
    para.innerHTML = type
    document.body.appendChild para

watch "keydown"
watch "keypress"
watch "keyup"
```

Running [here](http://smblott.computing.dcu.ie/escape.html).  Looks the same to me with or without Vimium.

To repeat...

> What behaviour would you like to see from Esc?

Perhaps it would be helpful if you could point us to a specific page, so we all have a specific use case in mind.

**Comment by ZombieHippie** [comment] 2015-01-06 14:49
I'm looking at your demo right now, this is specifically a case where it
breaks: http://codemirror.net/demo/sublime.html

It may have something to do with a focused input.

**Comment by ZombieHippie** [comment] 2015-01-06 14:54
It does have to do with an input being focused.
http://codepen.io/ZombieHippie/pen/zxoXwW

**Comment by smblott-github** [comment] 2015-01-06 14:56
I'm not sure what you want me to do.

I go to which page?
I do what?
What happens?
What do you want to happen?

**Comment by ZombieHippie** [comment] 2015-01-06 15:01
Sorry for lack of explanation :-)

If you go to my code pen http://codepen.io/ZombieHippie/pen/zxoXwW which I
include your escape.coffe code in, you will see differences between
pressing escape while the input is focused and when it isn't.

In the codepen click on the input to focus, then compare behaviors of
pressing Escape:

No Vimium: The input does not lose focus upon pressing escape.
Vimium: The input does lose focus upon pressing escape.

tested on Chrome 39

**Comment by smblott-github** [comment] 2015-01-06 15:14
Yes, that's right.  Because, when an input is focused, Vimium does grab and use `Esc`.  Thats a feature.

Now, what do you want to happen?  One possibility would be:
- If the page handles `Esc`, Vimium doesn't.
- Otherwise, it does.

But there are problems with this.
- Currently, Vimium handles the `Esc` before the page gets a chance to see it.  This is nearly always the right thing to do.  If it were otherwise, the Vimium UX would be different on different pages.
- We could wait to see whether the page uses the event.  However, it's not clear whether we could reliably detect that.

**Comment by smblott-github** [comment] 2015-01-06 15:16
In fact, taking the case of CodeMirror, we have no way of knowing whether the `Esc` was handled or not.  Their [handler](https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js#L667) returns `true` regardless of what it did.

**Comment by ZombieHippie** [comment] 2015-01-06 15:22
I can see where this feature is (very) desirable (if not required for
keyboard dedicated browsing), and I don't think there is an obvious
solution other than adjustable user preferences.

**Comment by ZombieHippie** [comment] 2015-01-06 15:24
Even if you could tell whether CodeMirror handled your Escape event, we
wouldn't have a different way to unfocus CodeMirror via keyboard.

**Comment by mrmr1993** [comment] 2015-01-06 16:00
Suggest #1372 for this, so `<esc>` can be a passkey.

**Comment by smblott-github** [comment] 2015-01-06 16:54
> Suggest #1372 for this, so <esc> can be a passkey.

I don't think so.  We're in insert mode, so none of the passkey code comes into play.

**Comment by mrmr1993** [comment] 2015-01-06 17:00
>I don't think so. 

I specifically designed it for this use case, it adds a passkey check to `exitInsertMode`.

**Comment by 00gavin** [comment] 2015-01-07 19:46
When using the Hangouts extension, Vimium prevents hitting Esc to close a chat window.  I would add a "Excluded URLs and keys" rule, but I don't know the "URL" of the extensions chat window.  What is the best way to fix this?  Thanks.

**Comment by 00gavin** [comment] 2015-01-07 20:00
AH.  Here is the fix...
1. Open chrome://extensions/ and click "Options" under the Hangouts extension
3. note the URL, something like chrome-extension://sadkjfhaklsjdhfkjhasdfkjh/settingsdialog.html
4. click the Vimium button
5. remove settingsdialog.html from the URL in the first box, keeping the *
6. don't hit the literal Esc key, but instead type the three letters Esc in the second box
7. click the Add Rule button

**Comment by mrmr1993** [comment] 2015-01-07 20:20
> 3. note the URL, something like chrome-extension://sadkjfhaklsjdhfkjhasdfkjh/settingsdialog.html
4. click the Vimium button
5. remove settingsdialog.html from the URL in the first box, keeping the *

Vimium can't run on `chrome-extension://` URLs for other extensions, so this will have no effect. If the chat windows do have a `chrome-extension://` URL then we're not blocking `<esc>` (or doing anything else) on them anyway.

> 6. don't hit the literal Esc key, but instead type the three letters Esc in the second box

This makes us pass `E`, `s`, and `c` to the page.

Currently we don't support the `<esc>` key (or any keys that aren't a single character) in the "Excluded URLs and keys" rule. I've created #1372 for this purpose, but it's not available at the moment. If/when it is, entering `<esc>` (separated by spaces from any other passkeys) should block the `<esc>` key.

> What is the best way to fix this?

If you find out what the chat window URLs are, you could block Vimium completely on them (assuming they're not `chrome-extension://` URLs). We don't provide anything else in options that would help at the moment.

**Comment by 00gavin** [comment] 2015-01-07 20:44
Thanks, Matt.  Bummer.  So no solution here.  Would love to see a built-in ignore for Hangout extension chat windows.  Cheers.

**Comment by dmonopoly** [comment] 2015-02-09 17:03
I would also like to see a way to pass <esc> to the list of ignored keys when wanting to ignore <esc> on certain sites. (Or maybe remap it universally to something else...)

**Comment by rrsahu** [comment] 2015-11-13 09:28
Bangalore is capital of India and known worldwide for its It industries, education centers, and living standard especially Bangalore . 

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>

**Comment by rrsahu** [comment] 2015-11-13 09:28
There all features attract young blood to start their career with a positive strategy. Also, they have to shift frequently from one place to other as soon as they change their current Company. 

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Comment by rrsahu** [comment] 2015-11-13 09:28
This is the purpose individuals in Bangalore are always looking for comfortable moving option that can help them in moving conveniently.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>

**Comment by rrsahu** [comment] 2015-11-13 09:29
Now it is simple to shift your valuables either it is individual, or electronic gadgets like TV, freeze, washing machines etc. it is true that you have to additional conscious when moving with any electronic gadgets or fragile components. 

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by zieren** [comment] 2016-03-06 11:39
+1 for supporting "unmap <esc>". Catching ESC makes working with Google Spreadsheets very annoying: When you entered something in a cell and want to abort, you need to press return and then undo because the normal way, pressing ESC, isn't propagated. Similarly for other apps.

Given that this issue is pretty old, maybe there's a workaround by now that I haven't managed to find?

**Comment by smblott-github** [comment] 2016-03-06 12:36
@zieren.  The next (full) release will have a `passNextKey` command.  See #1985.
That should catch your use case.
Closing.

**Closed by smblott-github** 2016-03-06 12:36 UTC

**Comment by avalanche1** [comment] 2019-04-03 08:41
So what is the solution for this?
I've tried adding `map <c-]><esc> passNextKey` as well as `map <c-]> passNextKey`, but I still cannot Esc in google sheets after editing a cell.

**Comment by gdh1995** [comment] 2019-04-03 11:22
Here's another idea to allow to pass much more keys: https://github.com/philc/vimium/issues/3272#issuecomment-475296695 .

**Comment by cool-RR** [comment] 2021-02-03 11:57
This issue is a problem for me as well. Can't use Vimium with Cider because it uses the Esc key. I don't even use any of Vimium's functionality that involves Esc keys.

**Comment by zereraz** [comment] 2023-07-07 08:08
Vimium is capturing Escape key for me as well. 
My frontend code was not working and after a lot of debugging eventually I just turned off Vimium and understood that it was the cause.

**Comment by ViktorQvarfordt** [comment] 2023-12-10 10:24
This is so annoying. If the user is not in any mode, why cant Escape just be sent to the underlying site?

**Comment by ezhang7423** [comment] 2024-03-13 04:16
+1, I would greatly appreciate a fix on this as well.

**Comment by ezhang7423** [comment] 2024-03-13 04:41
![image](https://github.com/philc/vimium/assets/54998055/c8de5a33-088b-4e75-87f5-c31607601e21)
I currently have this in my custom key mappings, and I do get the "Pass Next Key." dialog in the bottom right of my window. However, this doesn't seem to be working for exiting the github search modal, which is my primary usecase.
![image](https://github.com/philc/vimium/assets/54998055/1bf57811-04bc-41e6-a0b0-cd44f4271cbe)

**Comment by ezhang7423** [comment] 2024-03-13 04:46
Ah, solved this issue. You need to maintain focus on the modal, and then the escape will work:
![image](https://github.com/philc/vimium/assets/54998055/937cada6-eafc-4593-9865-9d3e80fe12fb)

Thank you for the hard work on this @smblott-github.
