### ISSUE TITLE
'prefers-color-scheme: dark' doesn't work in vomnibar

### ISSUE THREAD

**Issue by 0xhtml** [philc/vimium#4148] opened 2022-10-20 19:27 UTC
Since the latest Firefox update on Arch Linux the Vomnibar is no longer in dark mode. Firefox version: 106.0 64bit. The options page and all other websites are still respecting dark mode and it is even possible to force the prefers-color-scheme for the vomnibar through the developer tools.

**To Reproduce**
I freshly reset Firefox 106.0 (no bookmarks, no settings, no add-ons, nothing).
Then set Firefox theme to the default dark theme and selected dark as the default appearance of websites in the firefox settings.
Websites are now in dark mode.
Then installed vimium and pressed o (or O, b etc.) to open the vomnibar and it is light themed.
![20221020_21h10m03s_grim](https://user-images.githubusercontent.com/34682885/197038716-991b87b0-bcbe-4f41-aba7-5c8265829331.png)

I can however use the developer tools to enable the dark theme for the vomnibar.
![20221020_21h10m24s_grim](https://user-images.githubusercontent.com/34682885/197039417-96911622-1085-4e5b-9913-c8072f176649.png)

It seems to me like this issue was introduced by the Firefox update and not an update to vimium. It might be a bug in Firefox.

**Browser and Vimium version**

Firefox:
Version 	106.0
Build-ID 	20221017100737
Distributions-ID 	archlinux

Vimium-Version: 1.67.2

**Comment by gdh1995** [comment] 2022-10-21 04:14
Firefox 106 has changed how it deals with `color-scheme: light` on `<iframe>`, and then the solution in #3848 fails.

According to my tests, on Firefox 106, this works if in `content_scripts/vimium.css`:
``` css

.vimiumUIComponentVisible {
  color-scheme: normal;
}
```

**Comment by nikinbaidar** [comment] 2022-10-21 14:52
I've the same problem. The Vomnibar takes up light theme after the Firefox update. Trying 
```
.vimiumUIComponentVisible {
  color-scheme: normal;
}
```
or
```
.vimiumUIComponentVisible {
  color-scheme: dark;
}
```
does not seem to work on Arch Linux.

**Comment by nikinbaidar** [comment] 2022-10-21 15:11
I'd also like to add that the help dialog which was previously dark has now changed to a light theme too.

**Comment by DEAN-Cherry** [comment] 2022-10-29 04:19
> Firefox 106 has changed how it deals with `color-scheme: light` on `<iframe>`, and then the solution in #3848 fails.
> 
> According to my tests, on Firefox 106 and Win11, this works if in `content_scripts/vimium.css`:
> 
> ```css
> .vimiumUIComponentVisible {
>   color-scheme: normal;
> }
> ```
> 
> But on Chrome 102/106 and Win11, `normal` doesn't work while `light` succeeds.

So what can we do to solve this issue? This file seems to be unchangeable.

**Comment by gdh1995** [comment] 2022-10-29 04:45
@nikinbaidar How did you test it?
- `CSS for Vimium UI` won't work, because Vomnibar is inside a Shadow DOM tree, and the CSS won't be injected into it.
- If you downloaded Vimium source code and loaded it as a temporary extension, then you may need to reload the extension and your test page, so that Vimium can load latest file changes.

@DEAN-Cherry  Um yes Firefox's extension files are always packaged into a single file. So:
1. you may load Vimium source code as a temporary extension on `about:debugging#/runtime/this-firefox`, and apply the changes
- 1. in this way, please note that Firefox clears "temporary extensions" on closing, so you have to keep your Firefox open
- 2. or you have to load the customized version of Vimium everytime Firefox starts
3. or just wait a further version of Vimium to fix it.

**Comment by philc** [comment] 2022-10-29 17:56
Thanks for investigating the solution @gdh1995. Tricky.

**Closed** 2022-10-29 17:56 UTC

**Comment by nikinbaidar** [comment] 2022-10-30 06:45
The update to 106.0.2 fixed it.

**Comment by gdh1995** [comment] 2022-10-31 08:36
Reproduced on https://github.com/settings/appearance + `GitHub light/dark theme` + `Firefox 106.0.3 in Light/Dark theme` + `dark theme enabled in DevTools` and also reported in #4156 .

**Comment by gearonix** [comment] 2024-06-21 15:30
Still issue with dark reader extension
