### ISSUE TITLE
Do not select hidden tab when moving to adjacent tab

### ISSUE THREAD

**Issue by gagarine** [philc/vimium#3180] opened 2018-11-06 20:19 UTC
Using the shortcut `J, gT` or `K, gt ` let you select the right or left tab of the current tab.

Firefox web extension API let extension hide tab (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide) . For example with https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/ you can create tab group, only the tab from the active group are visible the other are hidden.

But vimium seem to select those tab, instead of moving to the adjacent tab, it select the hidden tab an activate the group of this tab hiding all my other tab. Using simple tab groups make this feature of vimium pretty much unusable.

Vimium should not select hidden tabs and only move trough active tabs.

**Comment by 0xf0cd** [comment] 2020-10-29 08:46
Just discovered this extension the other day, but **this** is the only thing annoying me so far. I use firefox and simple-tab-groups and vimium's _go one tab left/right_ doesn't work correctly, it jumps around tab groups. Guessing it could be fixed if go one tab left/right functioned like firefox cycle tabs ```CTRL + [SHIFT] + TAB```

**Comment by gdh1995** [comment] 2020-10-29 08:50
Hello, you may try my customized version of Vimium, named Vimium C, and I've fixed quite a few issues on Firefox.

**Comment by philc** [comment] 2024-05-30 04:38
This is a duplicate of #2998.

**Closed by philc** 2024-05-30 04:38 UTC
