### ISSUE TITLE
Custom CSS not applied to new pages

### ISSUE THREAD

**Issue by dawsdep** [philc/vimium#3452] opened 2020-01-02 04:42 UTC
I have some custom CSS set (which is a much appreciated feature) but there are times when the default styles are still applied until I reload the page.

Steps to reproduce the behavior (90% consistent):
1. Press 't' to open a new tab
2. Type in a search and hit enter
3. Press 'f' for link hints

Since it only seems to happen on a new page and not every single time, maybe there's something happening while things are loading or initializing? 

With custom CSS:
![Screen Shot 2020-01-01 at 8 33 16 PM](https://user-images.githubusercontent.com/9157052/71651924-55a93f00-2cd6-11ea-9cfd-683cbd47f595.png)

Custom CSS not being applied:
![Screen Shot 2020-01-01 at 8 32 53 PM](https://user-images.githubusercontent.com/9157052/71651929-5f32a700-2cd6-11ea-8e4d-af5632413f6b.png)

Chrome: 79.0.3945.88
Vimium: 1.64.6
macOS: 10.15.2

**Comment by gdh1995** [comment] 2020-01-02 05:02
Seems a duplicate of #3418 and would be worked around by #3421.

**Comment by d3ddd** [comment] 2020-01-02 05:16
I saw that issue but thought this might be different since it's not involving iframes? I'm happy to close this if it's the same thing.

**Comment by gdh1995** [comment] 2020-01-02 05:20
If I remembered it correctly, when I tested the old issue I also reproduced it on single-frame pages, and the PR does not deal with iframes differently.

**Comment by travankor** [comment] 2020-02-26 20:39
I run into this issue, too.

**Comment by parogen** [comment] 2020-05-22 00:00
Still running into this issue

**Comment by He4eT** [comment] 2020-08-27 21:38
I regularly encounter this problem too :c

**Comment by duckyb** [comment] 2020-09-29 14:25
@gdh1995 adding onto this issue;

I think the style for the background of the searched text is broken, i tried both `color` and `background-color` and nothing changed.

**Comment by sebastian-65** [comment] 2020-10-04 21:07
Custom CSS seems to be ignored completely in my case (Vivaldi 3.3, Xubuntu 16.04.3).

Since there are troubles with custom CSS, is it possible to somehow replace / overwrite the default one?

**Comment by 0x462e41** [comment] 2020-12-14 18:24
I'm experiencing the same issue, and it's really annoying to have to reload each new tab to temporarily fix it. Has anyone found a way to make it work and always load the custom CSS instead of the default one? Thanks

**Comment by 0x462e41** [comment] 2020-12-19 05:10
I found a workaround. As @sebastian-65 thought, by overwriting the default configuration I managed to fix it. It's not ideal, but get the job done for now.

In the file "$XDG_CONFIG_HOME/chromium/Default/Extensions/<hash>/<version_number>/content_scripts/vimium.css" I changed the attributes of "div.internalVimiumHintMarker", "div.internalVimiumHintMarker span" and "div.internalVimiumInputHint" to match my custom CSS "hint" configuration. Even though I have lots of stuff in my custom CSS, the issue only affects the hint, so that was all I had to change.

Hope this helps someone.

**Comment by sebastian-65** [comment] 2020-12-19 07:28
I'm glad to hear you've made it @0x462e41!

I'm definitely gonna try it in couple of days. Thank you for your investigation!

**Comment by mcp292** [comment] 2021-04-12 20:27
Pretty cool link hints. Consider sharing the CSS on the [themes](https://github.com/philc/vimium/wiki/Theme) page.

**Comment by f-viktor** [comment] 2021-07-11 10:56
> I found a workaround. As @sebastian-65 thought, by overwriting the default configuration I managed to fix it. It's not ideal, but get the job done for now.
> 
> In the file "$XDG_CONFIG_HOME/chromium/Default/Extensions/<id_number>/<version_number>/content_scripts/vimium.css" I changed the attributes of "div.internalVimiumHintMarker", "div.internalVimiumHintMarker span" and "div.internalVimiumInputHint" to match my custom CSS "hint" configuration. Even though I have lots of stuff in my custom CSS, the issue only affects the hint, so that was all I had to change.
> 
> Hope this helps someone.

this no longer works, as chromium/brave now checks for modifications of plugins, and disables them if they no longer match their expected hash. :(

**Comment by BachoSeven** [comment] 2021-07-11 11:55
> this no longer works, as chromium now checks for modifications of plugins, and disables them if they no longer match their expected hash. :(

I mean, you can just download the source from github and load it as an unpacked extension from chrome://extensions in developer mode, so there is no hash verification and you can just edit the source as you wish.

**Comment by itajsh** [comment] 2021-08-05 23:48
Added the following code in main.js, and it seems to work.
Just found some examples online. It's first time that I write chrome extension code, so consider this experimental.

// This is already in main.js:

chrome.webNavigation.onCommitted.addListener(function({tabId, frameId}) {
  const cssConf = {
    frameId,
    code: Settings.get("userDefinedLinkHintCss"),
    runAt: "document_start"
  };
  return chrome.tabs.insertCSS(tabId, cssConf, () => chrome.runtime.lastError);
});

// I added this:

chrome.tabs.onCreated.addListener(insertCssForTab);
chrome.tabs.onUpdated.addListener(function(tabId, info, tab) {
  if (info.status == 'complete') {
    insertCssForTab(tab);
  }
});

function insertCssForTab(tab) {
  const tabId = tab.id;
  const cssConf = {
    allFrames: true,
    code: Settings.get("userDefinedLinkHintCss"),
    runAt: "document_start"
  };
  chrome.tabs.insertCSS(tabId, cssConf, () => chrome.runtime.lastError);
}

**Comment by gdh1995** [comment] 2021-08-06 05:48
@itajsh `runAt` supports `document_end`, so it's not needed to wait for `onUpdated(status: complete)`. So, you may call `insertCSS` in `onCommitted` twice and the second one should be like https://github.com/philc/vimium/pull/3421/files.

**Comment by itajsh** [comment] 2021-08-07 22:00
@gdh1995 OK, this seems to work too.
Could something like that be done in Vimium master?

**Comment by philc** [comment] 2023-08-12 22:13
This should now be fixed in Vimium on `master` (v2.0); see discussion in #3883. If you find you're still able to reproduce this with Vimium v2.0, please post detailed instructions to reproduce.

**Closed by philc** 2023-08-12 22:13 UTC

**Comment by gwuen** [comment] 2025-03-30 21:47
I have the problem of custom CSS for link hints not being applied inside iframes (looks more like #3418, but that issue was closed in favor of this one).

![Image](https://github.com/user-attachments/assets/6c1ad57d-3583-4fe1-ad80-590963b98ea7)

I'm on Arch Linux, running Firefox 136.0.1 and experiencing this with Vimium 2.1.2 (the latest release on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/)) as well as 2.2.1 (installed from source). Unfortunately, I can't say if this occurred with previous versions, as I'm a new user.

I have experienced this on multiple sites with iframes. The screenshot shows [vimium.github.io](https://vimium.github.io/), but you can also try it with any other iframe on a local page: `data:text/html,<iframe src="https://vimium.github.io/", height=100%, width=100%></iframe>`

Interestingly enough, a temporary fix is navigating to some other page in the same tab. When the page with the iframe is still cached and therefore not reloaded after switching back, the link hints look as intended. The link hint view does not even need to be shown for this to work, not before switching, nor on the other page – it even works with `about:newtab`, where the extension is not even allowed to load.

I have already tried increasing the specificity of my rules, but the Page Inspector confirms that inside iframes, the custom link hint CSS is not loaded in the first place. The HUD and other elements are, as far as I can tell, completely unaffected by this bug.
