### ISSUE TITLE
Opening link clears search query

### ISSUE THREAD

**Issue by EmperorEarth** [philc/vimium#3208] opened 2018-12-24 19:42 UTC
* Chrome Version: 71.0.3578.98 64-bit Stable
* Vimium Version: 1.64.2

**Comment by smblott-github** [comment] 2018-12-26 08:35
I don't understand what this means.

**Comment by smblott-github** [comment] 2018-12-27 06:43
By "clears the query" you mean that the HUD input containing the query disappears?

This is the intended behaviour.  The idea is that if the HUD loses the focus, then the user is finished with it.  It's the same with the vomnibar and the help page.

(I'm not sure we'd want to change that without a good reason.)

**Comment by EmperorEarth** [comment] 2018-12-30 04:37
no. as in if I press `n` or `N` again, it will say `No query to find`

**Comment by AeliusSaionji** [comment] 2019-02-22 00:27
I too think this is a problem.

The last search query should be remembered- so I can simply press `n` across different pages to search for the same text.

Right now, the search query is too easily reset. Having to retype the same search over and over is frustrating, and I find myself just falling back on firefox's internal search, because that remembers what I typed.

**Comment by AeliusSaionji** [comment] 2019-02-22 20:12
I believe this is the same issue: https://github.com/philc/vimium/issues/3217

**Comment by smblott-github** [comment] 2019-02-23 16:23
Yes.  There's definitely something broken.  I'll look into it.

**Comment by EmperorEarth** [comment] 2020-02-18 19:09
@smblott-github I think this is fixed? Not sure which version.

I'd like a second opinion before I close.

@0xC0FFEE @AeliusSaionji

**Comment by gdh1995** [comment] 2020-02-19 03:14
Maybe by #3222, which has been merged in v1.65 ? If you mean a query history item in FindMode can not be used in a new tab.

**Comment by AeliusSaionji** [comment] 2020-02-20 00:55
Seems to work across tabs + refreshes now. 👍

**Comment by philc** [comment] 2020-02-20 07:41
Cool; closing. Thanks!

**Closed by philc** 2020-02-20 07:41 UTC
