### ISSUE TITLE
Trouble with find in FF Quantum

### ISSUE THREAD

**Issue by Niroday** [philc/vimium#2962] opened 2018-02-20 14:48 UTC
Hello.
FF Quantum 58.0.2 (64-bit)
Vimium 1.63.1
From time to time text that i typing in / becomes allocated and the next symbol replaces everything in the / field. Looks like this: https://s13.postimg.org/5a6vwxmfb/vim.gif

**Comment by smblott-github** [comment] 2018-02-20 14:53
Can you reliably reproduce this at all, @Niroday?  In the gif, is it going to "0 Matches" or "1 Match" at the end?

**Comment by Niroday** [comment] 2018-02-20 14:59
@smblott-github 
"No matches" after "conn" and 400 after replacing "conn" with "e". 
Yes, i can reproduce.

**Comment by Niroday** [comment] 2018-02-20 15:10
The first thing i thought was it's for quick deleting, but replacing with the next symbol displelled my doubts.

**Comment by smblott-github** [comment] 2018-02-20 15:18
Well, it's something related to `inputElement` [here](https://github.com/philc/vimium/blob/master/pages/hud.coffee).  But nothing there looks suspicious, to me.

**Comment by JohnVonNeumann** [comment] 2018-02-21 22:28
Probably redundant but came here to submit the issue, also having problems with find, pretty much straight after the most recent update.

**Comment by txomon** [comment] 2018-02-22 11:19
I have seen this in some pages, I have no idea on what could be causing it. This is one of them http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html

**Comment by redblade7** [comment] 2018-02-22 19:38
Having this exact same problem as of recently with Waterfox 56.0.4.1.

**Comment by smblott-github** [comment] 2018-02-23 07:31
Tried this myself.

It looks like, when there is no match, `window.find()` is finding the only match on the page, the one in the HUD.  Once the text in the HUD is selected, then next key clears the input.

There seem to be other changes to the behaviour of `window.find()`; for example, search no longer seems to wrap.

**Comment by gdh1995** [comment] 2018-02-23 12:01
@smblott-github I suggest that change https://github.com/philc/vimium/blob/master/content_scripts/mode_find.coffee#L180 's second `true` into `false` (arg "aSearchInFrames"), which should be useful. In my tests, Chrome does not support this argument and always returns `false` if a query is not in current frame.

Refer: https://developer.mozilla.org/en-US/docs/Web/API/Window/find

**Comment by smblott-github** [comment] 2018-02-23 12:25
Great suggestion, @gdh1995.  That seems to fix it.

**Comment by smblott-github** [comment] 2018-02-23 12:59
Fixed in 1bfe474a95f8eb23060cd42ff088146b5463dc62.

I'm minded to post publish this for FF as v1.63.1.

**Closed** 2018-02-23 12:58 UTC
