### ISSUE TITLE
Multiple websites: can't write after focusing on input fields

### ISSUE THREAD

**Issue by infokiller** [philc/vimium#2112] opened 2016-04-22 20:40 UTC
This issue happens only occasionally and I don't know how to reproduce it reliably. It's always resolved after refreshing the page. I'm not sure whether it's related to #1978. 

`chrome://version/`:
```
Google Chrome	50.0.2661.75 (Official Build) (64-bit)
```
Vimium version `1.54`.

**Comment by smblott-github** [comment] 2016-04-23 15:27
Do you mean "after focusing input by clicking with the mouse"?

**Comment by infokiller** [comment] 2016-04-23 23:33
No, I mean after focusing on the input using Vimium's commands- `gi` to focus on the first input field and then tab to iterate.

**Comment by smblott-github** [comment] 2016-04-24 10:55
@infokiller... Could you try using link hints to select the input (instead of `gf`) for a bit, and see if you still get the problem?

(Link hints simulates actually clicking the input, whereas `gf` just focuses it - so there might be a different effect.)

**Comment by infokiller** [comment] 2016-04-24 20:15
Sure, the next time this issue is manifested I'll try that and report back.

**Comment by infokiller** [comment] 2016-05-17 13:46
Over the last few days this has happened multiple times in various other websites. I tried using link hints and it doesn't help- I still can't type characters inside the input field. Moreover, I can't type **even if I click on the input field with the mouse**. So, I'm not even sure if it's because of Vimium.
I currently have Google Translate open in a tab with that issue. Any ideas how to debug this?

Thanks!

**Comment by infokiller** [comment] 2016-05-17 13:53
Also: when I click on the text area there's no text cursor (caret) blinking.

**Comment by smblott-github** [comment] 2016-05-17 13:58
@infokiller.  Do you have *Don't let pages steal the focus on load* enabled on the options page?  If so, try disabling it for a bit. I found a bug (a race condition) in the *Grab-back-focus* code a while back (https://github.com/philc/vimium/commit/77a2c6b41959f978147bd953ac94f5484394b276).

**Comment by infokiller** [comment] 2016-05-17 23:21
Yes, I do. I'll try disabling it.

**Comment by infokiller** [comment] 2016-05-21 18:13
So I tried disabling *Don't let pages steal the focus on load* for the last few days, and I didn't have a single instance of this issue. Usually I'd hit this issue multiple times over this time period, so it seems highly correlated.

**Comment by smblott-github** [comment] 2016-05-23 14:53
Thanks for the update, @infokiller.  Looks like we're narrowing things down a bit.

I guess you don't have a reproducible case (or you would have posted it), right?

Could you try the following, please?

- Re-enable grab-back focus (on the options page).
- Wait until you can trigger the problem (just once will do).
- Then repeat whatever it is that you just did, and report back here whether the URL changed when you selected the input.

Thanks.

**Comment by infokiller** [comment] 2016-05-24 06:40
Yup, I'm not sure how to reproduce it. It seems that it triggers occasionally when I open a new tab. I haven't seen a case where it triggers when I'm already in an existing webpage and its input fields were working since the last reload.

Yes, no problem, I'll follow these steps. I can also do more elaborate debugging if you want- just let me know.

Thank you!

**Comment by innaterebel** [comment] 2016-05-24 23:38
I think I got it. This happens when `Ctrl` is keeping pressed down _alone_ when a foreground page is loading.

For simple reproduction, on a page with an input field in viewport, keeping `Ctrl` pressed then click the reload button of browser (don't press `F5` or `R` key, it will make `Ctrl` a modifier).
After the page reloaded, now you are impossible to do any input into the field even with mouse.

Reproes reliably for me. I have the _Don't let pages steal the focus on load_ option enabled.
Chrome 52.0.2739.0
Vimium 1.54

**Comment by infokiller** [comment] 2016-05-25 20:13
@innaterebel that doesn't reproduce for me.

**Comment by smblott-github** [comment] 2016-05-26 04:41
Doesn't reproduce for me either, @innaterebel.

**Comment by innaterebel** [comment] 2016-05-26 21:58
Well, I cannot reproduce it with Vimium 1.55 neither now. Guess your race condition patch fixed it anyway.

**Comment by smblott-github** [comment] 2016-05-27 09:32
@infokiller.  Vimium 1.55 is out.  We haven't quite tracked down the problem you've been having.  However, I experienced a similar problem previously, and that's been fixed.  Hopefully your problem is fixed too.

I'll close this for now.  Shout if you experience this problem going forward.  OK?

**Closed by smblott-github** 2016-05-27 09:32 UTC

**Comment by infokiller** [comment] 2016-05-27 12:47
Sounds good.
