### ISSUE TITLE
Keyboard letters not working to follow links

### ISSUE THREAD

**Issue by Rosseiro** [philc/vimium#1900] opened 2015-11-21 06:27 UTC
Hi, I'm using Google Chrome 46.0.2490.86 m, and (presumably) the latest version of Vimium. Sometimes when I begin the navigation with "F", the follow-up letters don't get to lead to the chosen link in the end. I see the letters fading, indicating they've been hit, but after hitting the entire sequence shown on screen the link is still not accessed. Other times I have an impression that it suggests the same key sequence for more than one link.

This never happens in Firefox with the VimFx extension.

Please look into it :)

**Comment by smblott-github** [comment] 2015-11-21 09:16
You say "sometimes".  Can you reliably reproduce this?  It would be great
to have a page where we can reproduce this.

**Comment by Rosseiro** [comment] 2015-12-08 23:36
Sorry for the long time for the feeback (18 days!).
Since I believe none else has faced this issue, I've come across the idea that this may be related to AutoHotKey. I have a hotstrings script (defined abbreviations and expansions) that internally works using the Backspace key. For instance, if I type `btw`, AHK will "hit" backspace twice (leaving the initial *B*) and then complete with `y the way`. So maybe some of the key suggestions popped up by Vimium had a conflict (correspondence) with my hotstrings, I mean, my abbreviations.

Thanks for your attention anyway :)

**Comment by dragon788** [comment] 2015-12-12 17:17
I've just noticed this today as well, and it does seem to be related to my enabling AutoHotKey today. I'm not 100% sure it is just AHK as it also seems that using the numbers for f/F works fine, its only using letters that seems to fail.

**Comment by Rosseiro** [comment] 2015-12-13 19:05
No, actually this has not anything to do with the "Use the link's name and numbers for link-hint filtering" option. That was never enabled. In fact I just tried it just now that you said it, but I think typing "F" then some numbers is not as comfortable and fast as typing letters :)

**Comment by smblott-github** [comment] 2016-01-30 12:55
Closing.
Seems to be an unfortunate feature interaction with another extension.

**Closed by smblott-github** 2016-01-30 12:55 UTC
