### ISSUE TITLE
feature request for howering a clickable/hoverable object.

### ISSUE THREAD

**Issue by aranmohyeddin** [philc/vimium#3074] opened 2018-07-30 13:20 UTC
I think it's create if there is a feature for that for example it can be very useful if we can hover clickable links in Wikipedia text to get the preview for them. Of course there should be someway to stop the hover(click the preview) also.

**Comment by brw** [comment] 2018-08-09 20:52
Duplicate of #2174

**Closed** 2018-08-10 13:04 UTC
